origin
GIT 53262d12d1658669029ab39a63e3d314108abe66

commit 5d96e0cba26323c3daeb9f7cdfd4efe70985e2c6
Author: Jungseok Lee <jungseoklee85@gmail.com>
Date:   Sat Dec 20 00:49:40 2014 +0000

    arm64: mm: Add pgd_page to support RCU fast_gup
    
    This patch adds pgd_page definition in order to keep supporting
    HAVE_GENERIC_RCU_GUP configuration. In addition, it changes pud_page
    expression to align with pmd_page for readability.
    
    An introduction of pgd_page resolves the following build breakage
    under 4KB + 4Level memory management combo.
    
    mm/gup.c: In function 'gup_huge_pgd':
    mm/gup.c:889:2: error: implicit declaration of function 'pgd_page' [-Werror=implicit-function-declaration]
      head = pgd_page(orig);
      ^
    mm/gup.c:889:7: warning: assignment makes pointer from integer without a cast
      head = pgd_page(orig);
    
    Cc: Will Deacon <will.deacon@arm.com>
    Cc: Steve Capper <steve.capper@linaro.org>
    Signed-off-by: Jungseok Lee <jungseoklee85@gmail.com>
    [catalin.marinas@arm.com: remove duplicate pmd_page definition]
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

commit f7bf130ecd01f6c9d95c02c7a83d5d9dc263b0c9
Author: Will Deacon <will.deacon@arm.com>
Date:   Sun Dec 21 11:13:12 2014 +0000

    arm64: defconfig: defconfig update for 3.19
    
    The usual defconfig tweaks, this time:
    
      - FHANDLE and AUTOFS4_FS to keep systemd happy
      - PID_NS, QUOTA and KEYS to keep LTP happy
      - Disable DEBUG_PREEMPT, as this *really* hurts performance
    
    Signed-off-by: Will Deacon <will.deacon@arm.com>
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

commit f43c27188a49111b58e9611afa2f0365b0b55625
Author: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
Date:   Fri Dec 19 17:03:47 2014 +0000

    arm64: kernel: fix __cpu_suspend mm switch on warm-boot
    
    On arm64 the TTBR0_EL1 register is set to either the reserved TTBR0
    page tables on boot or to the active_mm mappings belonging to user space
    processes, it must never be set to swapper_pg_dir page tables mappings.
    
    When a CPU is booted its active_mm is set to init_mm even though its
    TTBR0_EL1 points at the reserved TTBR0 page mappings. This implies
    that when __cpu_suspend is triggered the active_mm can point at
    init_mm even if the current TTBR0_EL1 register contains the reserved
    TTBR0_EL1 mappings.
    
    Therefore, the mm save and restore executed in __cpu_suspend might
    turn out to be erroneous in that, if the current->active_mm corresponds
    to init_mm, on resume from low power it ends up restoring in the
    TTBR0_EL1 the init_mm mappings that are global and can cause speculation
    of TLB entries which end up being propagated to user space.
    
    This patch fixes the issue by checking the active_mm pointer before
    restoring the TTBR0 mappings. If the current active_mm == &init_mm,
    the code sets the TTBR0_EL1 to the reserved TTBR0 mapping instead of
    switching back to the active_mm, which is the expected behaviour
    corresponding to the TTBR0_EL1 settings when __cpu_suspend was entered.
    
    Fixes: 95322526ef62 ("arm64: kernel: cpu_{suspend/resume} implementation")
    Cc: <stable@vger.kernel.org> # 3.14+: 18ab7db
    Cc: <stable@vger.kernel.org> # 3.14+: 714f599
    Cc: <stable@vger.kernel.org> # 3.14+: c3684fb
    Cc: <stable@vger.kernel.org> # 3.14+
    Cc: Will Deacon <will.deacon@arm.com>
    Signed-off-by: Lorenzo Pieralisi <lorenzo.pieralisi@arm.com>
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>

commit 48ec833b7851438f02164ea846852ce4696f09ad
Author: Kirill A. Shutemov <kirill.shutemov@linux.intel.com>
Date:   Mon Dec 22 21:01:54 2014 +0200

    Revert "mm/memory.c: share the i_mmap_rwsem"
    
    This reverts commit c8475d144abb1e62958cc5ec281d2a9e161c1946.
    
    There are several[1][2] of bug reports which points to this commit as potential
    cause[3].
    
    Let's revert it until we figure out what's going on.
    
    [1] https://lkml.org/lkml/2014/11/14/342
    [2] https://lkml.org/lkml/2014/12/22/213
    [3] https://lkml.org/lkml/2014/12/9/741
    
    Signed-off-by: Kirill A. Shutemov <kirill.shutemov@linux.intel.com>
    Reported-by: Sasha Levin <sasha.levin@oracle.com>
    Acked-by: Davidlohr Bueso <dave@stgolabs.net>
    Cc: Hugh Dickins <hughd@google.com>
    Cc: Oleg Nesterov <oleg@redhat.com>
    Cc: Peter Zijlstra (Intel) <peterz@infradead.org>
    Cc: Rik van Riel <riel@redhat.com>
    Cc: Srikar Dronamraju <srikar@linux.vnet.ibm.com>
    Cc: Mel Gorman <mgorman@suse.de>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit 31dde116cb084bc0042cafe48975ffb7d1a4ae5d
Author: Catalin Marinas <catalin.marinas@arm.com>
Date:   Thu Dec 18 17:13:49 2014 +0000

    arm64: Replace set_arch_dma_coherent_ops with arch_setup_dma_ops
    
    Commit a3a60f81ee6f (dma-mapping: replace set_arch_dma_coherent_ops with
    arch_setup_dma_ops) changes the of_dma_configure() arch dma_ops callback
    to arch_setup_dma_ops but only the arch/arm code is updated. Subsequent
    commit 97890ba9289c (dma-mapping: detect and configure IOMMU in
    of_dma_configure) changes the arch_setup_dma_ops() prototype further to
    handle iommu. The patch makes the corresponding arm64 changes.
    
    Signed-off-by: Catalin Marinas <catalin.marinas@arm.com>
    Reported-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Will Deacon <will.deacon@arm.com>

commit 5164bece1673cdf04782f8ed3fba70743700f5da
Author: zhendong chen <alex.chen@huawei.com>
Date:   Wed Dec 17 14:37:04 2014 +0800

    dm: fix missed error code if .end_io isn't implemented by target_type
    
    In bio-based DM's clone_endio(), when target_type doesn't implement
    .end_io (e.g. linear) r will be always be initialized 0.  So if a
    WRITE SAME bio fails WRITE SAME will not be disabled as intended.
    
    Fix this by initializing r to error, rather than 0, in clone_endio().
    
    Signed-off-by: Alex Chen <alex.chen@huawei.com>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>
    Fixes: 7eee4ae2db ("dm: disable WRITE SAME if it fails")
    Cc: stable@vger.kernel.org

commit 2b94e8960cc3f225dec058f27570505351f4bc13
Author: Marc Dionne <marc.c.dionne@gmail.com>
Date:   Wed Dec 17 07:59:59 2014 -0500

    dm thin: fix crash by initializing thin device's refcount and completion earlier
    
    Commit 80e96c5484be ("dm thin: do not allow thin device activation
    while pool is suspended") delayed the initialization of a new thin
    device's refcount and completion until after this new thin was added
    to the pool's active_thins list and the pool lock is released.  This
    opens a race with a worker thread that walks the list and calls
    thin_get/put, noticing that the refcount goes to 0 and calling
    complete, freezing up the system and giving the oops below:
    
     kernel: BUG: unable to handle kernel NULL pointer dereference at           (null)
     kernel: IP: [<ffffffff810d360b>] __wake_up_common+0x2b/0x90
    
     kernel: Call Trace:
     kernel: [<ffffffff810d3683>] __wake_up_locked+0x13/0x20
     kernel: [<ffffffff810d3dc7>] complete+0x37/0x50
     kernel: [<ffffffffa0595c50>] thin_put+0x20/0x30 [dm_thin_pool]
     kernel: [<ffffffffa059aab7>] do_worker+0x667/0x870 [dm_thin_pool]
     kernel: [<ffffffff816a8a4c>] ? __schedule+0x3ac/0x9a0
     kernel: [<ffffffff810b1aef>] process_one_work+0x14f/0x400
     kernel: [<ffffffff810b206b>] worker_thread+0x6b/0x490
     kernel: [<ffffffff810b2000>] ? rescuer_thread+0x260/0x260
     kernel: [<ffffffff810b6a7b>] kthread+0xdb/0x100
     kernel: [<ffffffff810b69a0>] ? kthread_create_on_node+0x170/0x170
     kernel: [<ffffffff816ad7ec>] ret_from_fork+0x7c/0xb0
     kernel: [<ffffffff810b69a0>] ? kthread_create_on_node+0x170/0x170
    
    Set the thin device's initial refcount and initialize the completion
    before adding it to the pool's active_thins list in thin_ctr().
    
    Signed-off-by: Marc Dionne <marc.dionne@your-file-system.com>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>

commit 2c43fd26e46734430122b8d2ad3024bb532df3ef
Author: Joe Thornber <ejt@redhat.com>
Date:   Thu Dec 11 11:12:19 2014 +0000

    dm thin: fix missing out-of-data-space to write mode transition if blocks are released
    
    Discard bios and thin device deletion have the potential to release data
    blocks.  If the thin-pool is in out-of-data-space mode, and blocks were
    released, transition the thin-pool back to full write mode.
    
    The correct time to do this is just after the thin-pool metadata commit.
    It cannot be done before the commit because the space maps will not
    allow immediate reuse of the data blocks in case there's a rollback
    following power failure.
    
    Signed-off-by: Joe Thornber <ejt@redhat.com>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>
    Cc: stable@vger.kernel.org

commit 45ec9bd0fd7abf8705e7cf12205ff69fe9d51181
Author: Joe Thornber <ejt@redhat.com>
Date:   Wed Dec 10 17:06:57 2014 +0000

    dm thin: fix inability to discard blocks when in out-of-data-space mode
    
    When the pool was in PM_OUT_OF_SPACE mode its process_prepared_discard
    function pointer was incorrectly being set to
    process_prepared_discard_passdown rather than process_prepared_discard.
    
    This incorrect function pointer meant the discard was being passed down,
    but not effecting the mapping.  As such any discard that was issued, in
    an attempt to reclaim blocks, would not successfully free data space.
    
    Reported-by: Eric Sandeen <sandeen@redhat.com>
    Signed-off-by: Joe Thornber <ejt@redhat.com>
    Signed-off-by: Mike Snitzer <snitzer@redhat.com>
    Cc: stable@vger.kernel.org
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>