x86, mm: fix NOHIGHMEM && X86_PAE build config for native_pud_clear()
Looks like a 32bit x86 build failure case where X86_PAE and NOHIMEM
are on. This was reported by kbuild test bot.

   In file included from include/linux/mm.h:68:0,
                    from include/linux/highmem.h:7,
                    from include/linux/bio.h:21,
                    from include/linux/writeback.h:205,
                    from include/linux/memcontrol.h:30,
                    from include/linux/swap.h:8,
                    from include/linux/suspend.h:4,
                    from arch/x86/kernel/asm-offsets.c:12:
   arch/x86/include/asm/pgtable.h: In function 'native_local_pudp_get_and_clear':
>> arch/x86/include/asm/pgtable.h:888:2: error: implicit declaration of function 'native_pud_clear' [-Werror=implicit-function-declaration]
     native_pud_clear(pudp);
     ^~~~~~~~~~~~~~~~

Fixes: a00cc7d9dd93d ("mm, x86: add support for PUD-sized transparent hugepages")
Link: http://lkml.kernel.org/r/148883869853.70777.12180810304957921737.stgit@djiang5-desk3.ch.intel.com
Signed-off-by: Dave Jiang <dave.jiang@intel.com>
Cc: Matthew Wilcox <mawilcox@microsoft.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>