origin
GIT 8f9cedc76fc7d9bc916127f8fe1287a249891d40

commit e7661a8e5ce10b5321882d0bbaf3f81070903319
Author: Johannes Thumshirn <jthumshirn@suse.de>
Date:   Wed Apr 12 09:21:19 2017 +0200

    scsi: return correct blkprep status code in case scsi_init_io() fails.
    
    When instrumenting the SCSI layer to run into the
    !blk_rq_nr_phys_segments(rq) case the following warning emitted from the
    block layer:
    
    blk_peek_request: bad return=-22
    
    This happens because since commit fd3fc0b4d730 ("scsi: don't BUG_ON()
    empty DMA transfers") we return the wrong error value from
    scsi_prep_fn() back to the block layer.
    
    [mkp: silenced checkpatch]
    
    Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
    Fixes: fd3fc0b4d730 scsi: don't BUG_ON() empty DMA transfers
    Cc: <stable@vger.kernel.org>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: Hannes Reinecke <hare@suse.com>
    Reviewed-by: Bart Van Assche <bart.vanassche@sandisk.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit edb0b6a0b4490014924d56c4c7117c7c8fc608ca
Author: Mathias Kresin <dev@kresin.me>
Date:   Sun Mar 26 19:05:36 2017 +0200

    MIPS: PCI: add controllers before the specified head
    
    With commit 23dac14d058f ("MIPS: PCI: Use struct list_head lists") new
    controllers are added after the specified head where they where added
    before the specified head previously.
    
    Use list_add_tail to restore the former order.
    
    This patches fixes the following PCI error on lantiq:
    
      pci 0000:01:00.0: BAR 0: error updating (0x1c000004 != 0x000000)
    
    Fixes: 23dac14d058f ("MIPS: PCI: Use struct list_head lists")
    Signed-off-by: Mathias Kresin <dev@kresin.me>
    Cc: linux-mips@linux-mips.org
    Patchwork: https://patchwork.linux-mips.org/patch/15808/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit 162b270c664dca2e0944308e92f9fcc887151a72
Author: James Hogan <james.hogan@imgtec.com>
Date:   Thu Mar 30 16:06:02 2017 +0100

    MIPS: KGDB: Use kernel context for sleeping threads
    
    KGDB is a kernel debug stub and it can't be used to debug userland as it
    can only safely access kernel memory.
    
    On MIPS however KGDB has always got the register state of sleeping
    processes from the userland register context at the beginning of the
    kernel stack. This is meaningless for kernel threads (which never enter
    userland), and for user threads it prevents the user seeing what it is
    doing while in the kernel:
    
    (gdb) info threads
      Id   Target Id         Frame
      ...
      3    Thread 2 (kthreadd) 0x0000000000000000 in ?? ()
      2    Thread 1 (init)   0x000000007705c4b4 in ?? ()
      1    Thread -2 (shadowCPU0) 0xffffffff8012524c in arch_kgdb_breakpoint () at arch/mips/kernel/kgdb.c:201
    
    Get the register state instead from the (partial) kernel register
    context stored in the task's thread_struct for resume() to restore. All
    threads now correctly appear to be in context_switch():
    
    (gdb) info threads
      Id   Target Id         Frame
      ...
      3    Thread 2 (kthreadd) context_switch (rq=<optimized out>, cookie=..., next=<optimized out>, prev=0x0) at kernel/sched/core.c:2903
      2    Thread 1 (init)   context_switch (rq=<optimized out>, cookie=..., next=<optimized out>, prev=0x0) at kernel/sched/core.c:2903
      1    Thread -2 (shadowCPU0) 0xffffffff8012524c in arch_kgdb_breakpoint () at arch/mips/kernel/kgdb.c:201
    
    Call clobbered registers which aren't saved and exception registers
    (BadVAddr & Cause) which can't be easily determined without stack
    unwinding are reported as 0. The PC is taken from the return address,
    such that the state presented matches that found immediately after
    returning from resume().
    
    Fixes: 8854700115ec ("[MIPS] kgdb: add arch support for the kernel's kgdb core")
    Signed-off-by: James Hogan <james.hogan@imgtec.com>
    Cc: Jason Wessel <jason.wessel@windriver.com>
    Cc: linux-mips@linux-mips.org
    Cc: stable@vger.kernel.org
    Patchwork: https://patchwork.linux-mips.org/patch/15829/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit bac06cf0fb9dfd79877a4eaa2ec7c09a6b853ffa
Author: Matt Redfearn <matt.redfearn@imgtec.com>
Date:   Fri Mar 31 11:51:08 2017 +0100

    MIPS: smp-cps: Fix potentially uninitialised value of core
    
    Turning on DEBUG in smp-cps.c, or compiling the kernel with
    CONFIG_DYNAMIC_DEBUG enabled results the build error:
    
    arch/mips/kernel/smp-cps.c: In function 'play_dead':
    ./include/linux/dynamic_debug.h:126:3: error: 'core' may be used
    uninitialized in this function [-Werror=maybe-uninitialized]
    
    Fix this by always initialising the variable.
    
    Fixes: 0d2808f338c7 ("MIPS: smp-cps: Add support for CPU hotplug of MIPSr6 processors")
    Signed-off-by: Matt Redfearn <matt.redfearn@imgtec.com>
    Cc: James Hogan <james.hogan@imgtec.com>
    Cc: Masahiro Yamada <yamada.masahiro@socionext.com>
    Cc: Paul Burton <paul.burton@imgtec.com>
    Cc: Ingo Molnar <mingo@kernel.org>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Cc: linux-mips@linux-mips.org
    Cc: linux-kernel@vger.kernel.org
    Patchwork: https://patchwork.linux-mips.org/patch/15848/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit ec62a3bd84df90a19b7d59d032fa807bbfea7cbb
Author: Matt Redfearn <matt.redfearn@imgtec.com>
Date:   Fri Mar 31 11:51:33 2017 +0100

    MIPS: KASLR: Add missing header files
    
    After the split of linux/sched.h, KASLR stopped building.
    
    Fix this by including the correct header file for init_thread_union
    
    Signed-off-by: Matt Redfearn <matt.redfearn@imgtec.com>
    Cc: James Hogan <james.hogan@imgtec.com>
    Cc: Marcin Nowakowski <marcin.nowakowski@imgtec.com>
    Cc: Steven J. Hill <Steven.Hill@cavium.com>
    Cc: linux-mips@linux-mips.org
    Cc: linux-kernel@vger.kernel.org
    Patchwork: https://patchwork.linux-mips.org/patch/15849/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit c46f59e90226fa5bfcc83650edebe84ae47d454b
Author: James Cowgill <James.Cowgill@imgtec.com>
Date:   Tue Apr 11 13:51:07 2017 +0100

    MIPS: Avoid BUG warning in arch_check_elf
    
    arch_check_elf contains a usage of current_cpu_data that will call
    smp_processor_id() with preemption enabled and therefore triggers a
    "BUG: using smp_processor_id() in preemptible" warning when an fpxx
    executable is loaded.
    
    As a follow-up to commit b244614a60ab ("MIPS: Avoid a BUG warning during
    prctl(PR_SET_FP_MODE, ...)"), apply the same fix to arch_check_elf by
    using raw_current_cpu_data instead. The rationale quoted from the previous
    commit:
    
    "It is assumed throughout the kernel that if any CPU has an FPU, then
    all CPUs would have an FPU as well, so it is safe to perform the check
    with preemption enabled - change the code to use raw_ variant of the
    check to avoid the warning."
    
    Fixes: 46490b572544 ("MIPS: kernel: elf: Improve the overall ABI and FPU mode checks")
    Signed-off-by: James Cowgill <James.Cowgill@imgtec.com>
    CC: <stable@vger.kernel.org> # 4.0+
    Cc: linux-mips@linux-mips.org
    Patchwork: https://patchwork.linux-mips.org/patch/15951/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit e0211327f068901ce654ba78951c35bc69fdc1de
Author: James Cowgill <James.Cowgill@imgtec.com>
Date:   Tue Apr 11 13:51:08 2017 +0100

    MIPS: Fix modversioning of _mcount symbol
    
    In commit 827456e71036 ("MIPS: Export _mcount alongside its definition")
    the EXPORT_SYMBOL macro exporting _mcount was moved from C code into
    assembly. Unlike C, exported assembly symbols need to have a function
    prototype in asm/asm-prototypes.h for modversions to work properly.
    Without this, modpost prints out this warning:
    
         WARNING: EXPORT symbol "_mcount" [vmlinux] version generation failed,
         symbol will not be versioned.
    
    Fix by including asm/ftrace.h (where _mcount is declared) in
    asm/asm-prototypes.h.
    
    Fixes: 827456e71036 ("MIPS: Export _mcount alongside its definition")
    Signed-off-by: James Cowgill <James.Cowgill@imgtec.com>
    Cc: linux-mips@linux-mips.org
    Patchwork: https://patchwork.linux-mips.org/patch/15952/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit 337b775b6cf5d093295961c1aa6ac76693b5f847
Author: Marcin Nowakowski <marcin.nowakowski@imgtec.com>
Date:   Mon Mar 13 15:57:14 2017 +0100

    MIPS: generic: fix out-of-tree defconfig target builds
    
    When specifying a generic defconfig target with O=... option set, make
    is invoked in the output location before a target makefile wrapper is
    created. Ensure that the correct makefile is used by specifying the
    kernel source makefile during make invocation.
    
    This fixes the either of the following errors:
    
    $ make sead3_defoncifg ARCH=mips O=test
    make[1]: Entering directory '/mnt/ssd/MIPS/linux-next/test'
    make[2]: *** No rule to make target '32r2el_defconfig'.  Stop.
    arch/mips/Makefile:506: recipe for target 'sead3_defconfig' failed
    make[1]: *** [sead3_defconfig] Error 2
    make[1]: Leaving directory '/mnt/ssd/MIPS/linux-next/test'
    Makefile:152: recipe for target 'sub-make' failed
    make: *** [sub-make] Error 2
    
    $ make 32r2el_defconfig ARCH=mips O=test
    make[1]: Entering directory '/mnt/ssd/MIPS/linux-next/test'
    Using ../arch/mips/configs/generic_defconfig as base
    Merging ../arch/mips/configs/generic/32r2.config
    Merging ../arch/mips/configs/generic/el.config
    Merging ../arch/mips/configs/generic/board-sead-3.config
    !
    ! merged configuration written to .config (needs make)
    !
    make[2]: *** No rule to make target 'olddefconfig'.  Stop.
    arch/mips/Makefile:489: recipe for target '32r2el_defconfig' failed
    make[1]: *** [32r2el_defconfig] Error 2
    make[1]: Leaving directory '/mnt/ssd/MIPS/linux-next/test'
    Makefile:152: recipe for target 'sub-make' failed
    make: *** [sub-make] Error 2
    
    Fixes: eed0eabd12ef ('MIPS: generic: Introduce generic DT-based board support')
    Fixes: 3f5f0a4475e1 ('MIPS: generic: Convert SEAD-3 to a generic board')
    Signed-off-by: Marcin Nowakowski <marcin.nowakowski@imgtec.com>
    Cc: Paul Burton <paul.burton@imgtec.com>
    Cc: linux-mips@linux-mips.org
    Patchwork: https://patchwork.linux-mips.org/patch/15464/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit 9d7f29cdb4ca53506115cf1d7a02ce6013894df0
Author: James Hogan <james.hogan@imgtec.com>
Date:   Wed Apr 5 16:32:45 2017 +0100

    MIPS: cevt-r4k: Fix out-of-bounds array access
    
    calculate_min_delta() may incorrectly access a 4th element of buf2[]
    which only has 3 elements. This may trigger undefined behaviour and has
    been reported to cause strange crashes in start_kernel() sometime after
    timer initialization when built with GCC 5.3, possibly due to
    register/stack corruption:
    
    sched_clock: 32 bits at 200MHz, resolution 5ns, wraps every 10737418237ns
    CPU 0 Unable to handle kernel paging request at virtual address ffffb0aa, epc == 8067daa8, ra == 8067da84
    Oops[#1]:
    CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.9.18 #51
    task: 8065e3e0 task.stack: 80644000
    $ 0   : 00000000 00000001 00000000 00000000
    $ 4   : 8065b4d0 00000000 805d0000 00000010
    $ 8   : 00000010 80321400 fffff000 812de408
    $12   : 00000000 00000000 00000000 ffffffff
    $16   : 00000002 ffffffff 80660000 806a666c
    $20   : 806c0000 00000000 00000000 00000000
    $24   : 00000000 00000010
    $28   : 80644000 80645ed0 00000000 8067da84
    Hi    : 00000000
    Lo    : 00000000
    epc   : 8067daa8 start_kernel+0x33c/0x500
    ra    : 8067da84 start_kernel+0x318/0x500
    Status: 11000402 KERNEL EXL
    Cause : 4080040c (ExcCode 03)
    BadVA : ffffb0aa
    PrId  : 0501992c (MIPS 1004Kc)
    Modules linked in:
    Process swapper/0 (pid: 0, threadinfo=80644000, task=8065e3e0, tls=00000000)
    Call Trace:
    [<8067daa8>] start_kernel+0x33c/0x500
    Code: 24050240  0c0131f9  24849c64 <a200b0a8> 41606020  000000c0  0c1a45e6 00000000  0c1a5f44
    
    UBSAN also detects the same issue:
    
    ================================================================
    UBSAN: Undefined behaviour in arch/mips/kernel/cevt-r4k.c:85:41
    load of address 80647e4c with insufficient space
    for an object of type 'unsigned int'
    CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.9.18 #47
    Call Trace:
    [<80028f70>] show_stack+0x88/0xa4
    [<80312654>] dump_stack+0x84/0xc0
    [<8034163c>] ubsan_epilogue+0x14/0x50
    [<803417d8>] __ubsan_handle_type_mismatch+0x160/0x168
    [<8002dab0>] r4k_clockevent_init+0x544/0x764
    [<80684d34>] time_init+0x18/0x90
    [<8067fa5c>] start_kernel+0x2f0/0x500
    =================================================================
    
    buf2[] is intentionally only 3 elements so that the last element is the
    median once 5 samples have been inserted, so explicitly prevent the
    possibility of comparing against the 4th element rather than extending
    the array.
    
    Fixes: 1fa405552e33f2 ("MIPS: cevt-r4k: Dynamically calculate min_delta_ns")
    Reported-by: Rabin Vincent <rabinv@axis.com>
    Signed-off-by: James Hogan <james.hogan@imgtec.com>
    Tested-by: Rabin Vincent <rabinv@axis.com>
    Cc: linux-mips@linux-mips.org
    Cc: <stable@vger.kernel.org> # 4.7.x-
    Patchwork: https://patchwork.linux-mips.org/patch/15892/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit f2b42866b1bb30c1f62a84f6d829b8789495da95
Author: Rabin Vincent <rabinv@axis.com>
Date:   Wed Apr 5 15:14:08 2017 +0200

    MIPS: perf: fix deadlock
    
    mipsxx_pmu_handle_shared_irq() calls irq_work_run() while holding the
    pmuint_rwlock for read.  irq_work_run() can, via perf_pending_event(),
    call try_to_wake_up() which can try to take rq->lock.
    
    However, perf can also call perf_pmu_enable() (and thus take the
    pmuint_rwlock for write) while holding the rq->lock, from
    finish_task_switch() via perf_event_context_sched_in().
    
    This leads to an ABBA deadlock:
    
     PID: 3855   TASK: 8f7ce288  CPU: 2   COMMAND: "process"
      #0 [89c39ac8] __delay at 803b5be4
      #1 [89c39ac8] do_raw_spin_lock at 8008fdcc
      #2 [89c39af8] try_to_wake_up at 8006e47c
      #3 [89c39b38] pollwake at 8018eab0
      #4 [89c39b68] __wake_up_common at 800879f4
      #5 [89c39b98] __wake_up at 800880e4
      #6 [89c39bc8] perf_event_wakeup at 8012109c
      #7 [89c39be8] perf_pending_event at 80121184
      #8 [89c39c08] irq_work_run_list at 801151f0
      #9 [89c39c38] irq_work_run at 80115274
     #10 [89c39c50] mipsxx_pmu_handle_shared_irq at 8002cc7c
    
     PID: 1481   TASK: 8eaac6a8  CPU: 3   COMMAND: "process"
      #0 [8de7f900] do_raw_write_lock at 800900e0
      #1 [8de7f918] perf_event_context_sched_in at 80122310
      #2 [8de7f938] __perf_event_task_sched_in at 80122608
      #3 [8de7f958] finish_task_switch at 8006b8a4
      #4 [8de7f998] __schedule at 805e4dc4
      #5 [8de7f9f8] schedule at 805e5558
      #6 [8de7fa10] schedule_hrtimeout_range_clock at 805e9984
      #7 [8de7fa70] poll_schedule_timeout at 8018e8f8
      #8 [8de7fa88] do_select at 8018f338
      #9 [8de7fd88] core_sys_select at 8018f5cc
     #10 [8de7fee0] sys_select at 8018f854
     #11 [8de7ff28] syscall_common at 80028fc8
    
    The lock seems to be there to protect the hardware counters so there is
    no need to hold it across irq_work_run().
    
    Signed-off-by: Rabin Vincent <rabinv@axis.com>
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>

commit 9eec1c01a073fe1fdba4e50e53bd953d1c59ad00
Author: Matt Redfearn <matt.redfearn@imgtec.com>
Date:   Thu Apr 6 16:58:09 2017 +0100

    MIPS: Malta: Fix i8259 irqchip setup
    
    Since commit 4cfffcfa5106 ("irqchip/mips-gic: Fix local interrupts"),
    the gic driver has been allocating virq's for local interrupts during
    its initialisation. Unfortunately on Malta platforms, these are the
    first IRQs to be allocated and so are allocated virqs 1-3. The i8259
    driver uses a legacy irq domain which expects to map virqs 0-15. Probing
    of that driver therefore fails because some of those virqs are already
    taken, with the warning:
    
    WARNING: CPU: 0 PID: 0 at kernel/irq/irqdomain.c:344
    irq_domain_associate+0x1e8/0x228
    error: virq1 is already associated
    Modules linked in:
    CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.10.0-rc6-00011-g4cfffcfa5106 #368
    Stack : 00000000 00000000 807ae03a 0000004d 00000000 806c1010 0000000b ffff0a01
            80725467 807258f4 806a64a4 00000000 00000000 807a9acc 00000100 80713e68
            806d5598 8017593c 8072bf90 8072bf94 806ac358 00000000 806abb60 80713ce4
            00000100 801b22d4 806d5598 8017593c 807ae03a 00000000 80713ce4 80720000
            00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
            ...
    Call Trace:
    [<8010c480>] show_stack+0x88/0xa4
    [<80376758>] dump_stack+0x88/0xd0
    [<8012c4a8>] __warn+0x104/0x118
    [<8012c4ec>] warn_slowpath_fmt+0x30/0x3c
    [<8017edfc>] irq_domain_associate+0x1e8/0x228
    [<8017efd0>] irq_domain_add_legacy+0x7c/0xb0
    [<80764c50>] __init_i8259_irqs+0x64/0xa0
    [<80764ca4>] i8259_of_init+0x18/0x74
    [<8076ddc0>] of_irq_init+0x19c/0x310
    [<80752dd8>] arch_init_irq+0x28/0x19c
    [<80750a08>] start_kernel+0x2a8/0x434
    
    Fix this by reserving the required i8259 virqs in malta platform code
    before probing any irq chips.
    
    Fixes: 4cfffcfa5106 ("irqchip/mips-gic: Fix local interrupts")
    Signed-off-by: Matt Redfearn <matt.redfearn@imgtec.com>
    Cc: James Hogan <james.hogan@imgtec.com>
    Cc: Paul Burton <paul.burton@imgtec.com>
    Cc: linux-mips@linux-mips.org
    Cc: linux-kernel@vger.kernel.org
    Patchwork: https://patchwork.linux-mips.org/patch/15919/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>