mm-mmu_notifier-avoid-double-notification-when-it-is-useless-checkpatch-fixes
WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#21: 
  A) page backing address is free before mmu_notifier_invalidate_range_end()

ERROR: code indent should use tabs where possible
#322: FILE: mm/hugetlb.c:3263:
+^I ^I^I^I *$

WARNING: please, no space before tabs
#322: FILE: mm/hugetlb.c:3263:
+^I ^I^I^I *$

total: 1 errors, 2 warnings, 283 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-mmu_notifier-avoid-double-notification-when-it-is-useless.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Jérôme Glisse <jglisse@redhat.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>