origin
GIT 9705596d08ac87c18aee32cc97f2783b7d14624e

commit 88931ec3dc11e7dbceb3b0df455693873b508fbe
Author: Allen Hubbe <Allen.Hubbe@dell.com>
Date:   Fri Jun 9 18:06:36 2017 -0400

    ntb: no sleep in ntb_async_tx_submit
    
    Do not sleep in ntb_async_tx_submit, which could deadlock.
    This reverts commit "8c874cc140d667f84ae4642bb5b5e0d6396d2ca4"
    
    Fixes: 8c874cc140d6 ("NTB: Address out of DMA descriptor issue with NTB")
    Reported-by: Jia-Ju Bai <baijiaju1990@163.com>
    Signed-off-by: Allen Hubbe <Allen.Hubbe@dell.com>
    Acked-by: Dave Jiang <dave.jiang@intel.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

commit 5eb449e15d2396785a8eb15baf42cea33db9ae13
Author: Dave Jiang <dave.jiang@intel.com>
Date:   Thu Jun 8 12:46:45 2017 -0700

    ntb: ntb_hw_intel: Skylake doorbells should be 32bits, not 64bits
    
    Fixing doorbell register length to 32bits per spec. On Skylake NTB, the
    doorbell registers are 32bit write only registers. The source for the
    doorbell is a 64bit register that shows the interrupt bits.
    
    Signed-off-by: Dave Jiang <dave.jiang@intel.com>
    Fixes: 783dfa6cc41b ("ntb: Adding Skylake Xeon NTB support")
    Acked-by: Allen Hubbe <Allen.Hubbe@dell.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

commit 8e8496e0e9564b66165f5219a4e8ed20b0d3fc6b
Author: Logan Gunthorpe <logang@deltatee.com>
Date:   Mon Jun 5 14:00:53 2017 -0600

    ntb_transport: fix bug calculating num_qps_mw
    
    A divide by zero error occurs if qp_count is less than mw_count because
    num_qps_mw is calculated to be zero. The calculation appears to be
    incorrect.
    
    The requirement is for num_qps_mw to be set to qp_count / mw_count
    with any remainder divided among the earlier mws.
    
    For example, if mw_count is 5 and qp_count is 12 then mws 0 and 1
    will have 3 qps per window and mws 2 through 4 will have 2 qps per window.
    Thus, when mw_num < qp_count % mw_count, num_qps_mw is 1 higher
    than when mw_num >= qp_count.
    
    Signed-off-by: Logan Gunthorpe <logang@deltatee.com>
    Fixes: e26a5843f7f5 ("NTB: Split ntb_hw_intel and ntb_transport drivers")
    Acked-by: Allen Hubbe <Allen.Hubbe@dell.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

commit cb827ee6ccc3e480f0d9c0e8e53eef55be5b0414
Author: Logan Gunthorpe <logang@deltatee.com>
Date:   Mon Jun 5 14:00:52 2017 -0600

    ntb_transport: fix qp count bug
    
    In cases where there are more mw's than spads/2-2, the mw count gets
    reduced to match the limitation. ntb_transport also tries to ensure that
    there are fewer qps than mws but uses the full mw count instead of
    the reduced one. When this happens, the math in
    'ntb_transport_setup_qp_mw' will get confused and result in a kernel
    paging request bug.
    
    This patch fixes the bug by reducing qp_count to the reduced mw count
    instead of the full mw count.
    
    Signed-off-by: Logan Gunthorpe <logang@deltatee.com>
    Fixes: e26a5843f7f5 ("NTB: Split ntb_hw_intel and ntb_transport drivers")
    Acked-by: Allen Hubbe <Allen.Hubbe@dell.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

commit 07b0b22b3e58824f70b9188d085d400069ca3240
Author: Logan Gunthorpe <logang@deltatee.com>
Date:   Mon Jun 5 10:13:24 2017 -0600

    NTB: ntb_test: fix bug printing ntb_perf results
    
    The code mistakenly prints the local perf results for the remote test
    so the script reports identical results for both directions. Fix this
    by ensuring we print the remote result.
    
    Signed-off-by: Logan Gunthorpe <logang@deltatee.com>
    Fixes: a9c59ef77458 ("ntb_test: Add a selftest script for the NTB subsystem")
    Acked-by: Allen Hubbe <Allen.Hubbe@dell.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

commit 94fc795454f461134cdffb88bef4eb9f788c0b5d
Author: Gary R Hook <gary.hook@amd.com>
Date:   Thu May 4 11:36:52 2017 -0500

    ntb: Correct modinfo usage statement for ntb_perf
    
    The order parameters are powers of 2; adjust the usage information
    to use correct mathematical representations.
    
    Signed-off-by: Gary R Hook <gary.hook@amd.com>
    Fixes: 8a7b6a778a85 ("ntb: ntb perf tool")
    Acked-by: Dave Jiang <dave.jiang@intel.com>
    Signed-off-by: Jon Mason <jdmason@kudzu.us>

commit d85da227c3ae43d9ca513d60f244213cb4e55485
Author: Chen-Yu Tsai <wens@csie.org>
Date:   Wed May 31 15:58:23 2017 +0800

    clk: sunxi-ng: a64: Export PLL_PERIPH0 clock for the PRCM
    
    The PRCM takes PLL_PERIPH0 as one of its parents for the AR100 clock.
    As such we need to be able to describe this relationship in the device
    tree.
    
    Export the PLL_PERIPH0 clock so we can reference it in the PRCM node.
    
    Signed-off-by: Chen-Yu Tsai <wens@csie.org>
    Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>

commit c4be8c68e6900b1811bc64f74cb13d5032a389ce
Author: Chen-Yu Tsai <wens@csie.org>
Date:   Wed May 31 15:58:21 2017 +0800

    clk: sunxi-ng: h3: Export PLL_PERIPH0 clock for the PRCM
    
    The PRCM takes PLL_PERIPH0 as one of its parents for the AR100 clock.
    As such we need to be able to describe this relationship in the device
    tree.
    
    Export the PLL_PERIPH0 clock so we can reference it in the PRCM node.
    
    Signed-off-by: Chen-Yu Tsai <wens@csie.org>
    Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>

commit a91afc974ee8441940241e3c39c75d7b8f38e911
Author: Chen-Yu Tsai <wens@csie.org>
Date:   Wed May 31 15:58:19 2017 +0800

    dt-bindings: clock: sunxi-ccu: Add pll-periph to PRCM's needed clocks
    
    The AR100 clock in the PRCM has parents, one of which is pll-periph from
    the main CCU.
    
    Add it to the list of required clocks for the PRCM CCU.
    
    Signed-off-by: Chen-Yu Tsai <wens@csie.org>
    Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>

commit 370d9192719e6c174167888cf9240df2542e3b4b
Author: Boris Brezillon <boris.brezillon@free-electrons.com>
Date:   Wed May 24 18:34:29 2017 +0200

    clk: sunxi-ng: sun5i: Fix ahb_bist_clk definition
    
    AHB BIST gate is actually controlled with bit 7.
    
    This bug was detected while trying to use the NAND controller which is
    using the DMA engine to transfer data to the NAND.
    Since the ahb_bist_clk gate bit conflicts with the ahb_dma_clk gate bit,
    the core was disabling the DMA engine clock as part of its 'disable
    unused clks' procedure, which was causing all DMA transfers to fail after
    this point.
    
    Fixes: 5e73761786d6 ("clk: sunxi-ng: Add sun5i CCU driver")
    Cc: stable@vger.kernel.org
    Reported-by: Angus Ainslie <angus@akkea.ca>
    Signed-off-by: Boris Brezillon <boris.brezillon@free-electrons.com>
    Tested-by: Angus Ainslie <angus@akkea.ca>
    Reviewed-by: Chen-Yu Tsai <wens@csie.org>
    Signed-off-by: Michael Turquette <mturquette@baylibre.com>
    Link: lkml.kernel.org/r/1495643669-28221-1-git-send-email-boris.brezillon@free-electrons.com

commit f36afd38c5372a7cd5b363786fd62076c8b28427
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed May 17 23:19:01 2017 +0200

    clk: sunxi-ng: enable SUNXI_CCU_MP for PRCM
    
    The newly added PRCM CCU driver uses SUNXI_CCU_MP_WITH_MUX_GATE, which causes
    a link error when no other driver enables SUNXI_CCU_MP:
    
    drivers/clk/built-in.o:(.data+0x5c8c8): undefined reference to `ccu_mp_ops'
    
    This adds an explicit 'select' statement for it.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Chen-Yu Tsai <wens@csie.org>
    Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>

commit dbed87a9d3a857a86f602775b5845f5f6d9652b5
Author: Tobias Regnery <tobias.regnery@gmail.com>
Date:   Mon Apr 24 12:05:42 2017 +0200

    clk: meson: gxbb: fix build error without RESET_CONTROLLER
    
    With CONFIG_RESET_CONTROLLER=n we see the following link error in the
    meson gxbb clk driver:
    
    drivers/built-in.o: In function 'gxbb_aoclkc_probe':
    drivers/clk/meson/gxbb-aoclk.c:161: undefined reference to 'devm_reset_controller_register'
    
    Fix this by selecting the reset controller subsystem.
    
    Fixes: f8c11f79912d ("clk: meson: Add GXBB AO Clock and Reset controller driver")
    Signed-off-by: Tobias Regnery <tobias.regnery@gmail.com>
    Acked-by: Neil Armstrong <narmstrong@baylibre.com>
    [narmstrong: Added fixes-by tag]
    Signed-off-by: Neil Armstrong <narmstrong@baylibre.com>

commit 7ffc781ec46ef1e9aedb482f5f04425bd8bb2753
Author: Yong Deng <iemdey@gmail.com>
Date:   Fri May 5 18:31:57 2017 +0800

    clk: sunxi-ng: v3s: Fix usb otg device reset bit
    
    V3S's usb otg device reset bit should be 24, not 23.
    
    Cc: stable@vger.kernel.org
    Signed-off-by: Yong Deng <iemdey@gmail.com>
    Reviewed-By: Icenowy Zheng <icenowy@aosc.io>
    Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>

commit 38b8f823864707eb1cf331d2247608c419ed388c
Author: Chen-Yu Tsai <wens@csie.org>
Date:   Wed May 3 11:13:46 2017 +0800

    clk: sunxi-ng: a31: Correct lcd1-ch1 clock register offset
    
    The register offset for the lcd1-ch1 clock was incorrectly pointing to
    the lcd0-ch1 clock. This resulted in the lcd0-ch1 clock being disabled
    when the clk core disables unused clocks. This then stops the simplefb
    HDMI output path.
    
    Reported-by: Bob Ham <rah@settrans.net>
    Fixes: c6e6c96d8fa6 ("clk: sunxi-ng: Add A31/A31s clocks")
    Cc: stable@vger.kernel.org # 4.9.x-
    Signed-off-by: Chen-Yu Tsai <wens@csie.org>
    Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>