hwpoison-memcg-forcibly-uncharge-lru-pages-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#12: 
least not since 0a31bc97c80c ("mm: memcontrol: rewrite uncharge API")). 

ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#13: 
Each charge pins memcg (since e8ea14cc6ead ("mm: memcontrol: take a css

WARNING: line over 80 characters
#54: FILE: mm/memory-failure.c:544:
+		 * Poisoned page might never drop its ref count to 0 so we have to

total: 2 errors, 1 warnings, 21 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/hwpoison-memcg-forcibly-uncharge-lru-pages.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Michal Hocko <mhocko@suse.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>