origin
GIT 8a28d67457b613258aa0578ccece206d166f2b9f

commit 977bf062bba3eb8d03f66d5b4e227e5d7ebc1e08
Author: Benjamin Herrenschmidt <benh@kernel.crashing.org>
Date:   Tue Oct 27 17:20:05 2015 +0900

    powerpc/dma: dma_set_coherent_mask() should not be GPL only
    
    When turning this from inline to an exported function I was a bit
    over-eager and made it GPL only. This prevents the use of pretty much
    all non-GPL PCI driver which is a bit over the top. Let's bring it
    back in line with other architecture.
    
    Fixes: 817820b0226a ("powerpc/iommu: Support "hybrid" iommu/direct DMA ops for coherent_mask < dma_mask")
    Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
    Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>

commit a22c4d7e34402ccdf3414f64c50365436eba7b93
Author: Ming Lin <ming.l@ssi.samsung.com>
Date:   Thu Oct 22 09:59:42 2015 -0700

    block: re-add discard_granularity and alignment checks
    
    In commit b49a087("block: remove split code in
    blkdev_issue_{discard,write_same}"), discard_granularity and alignment
    checks were removed. Ideally, with bio late splitting, the upper layers
    shouldn't need to depend on device's limits.
    
    Christoph reported a discard regression on the HGST Ultrastar SN100 NVMe
    device when mkfs.xfs. We have not found the root cause yet.
    
    This patch re-adds discard_granularity and alignment checks by reverting
    the related changes in commit b49a087. The good thing is now we can
    remove the 2G discard size cap and just use UINT_MAX to avoid bi_size
    overflow.
    
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Tested-by: Christoph Hellwig <hch@lst.de>
    Signed-off-by: Ming Lin <ming.l@ssi.samsung.com>
    Reviewed-by: Mike Snitzer <snitzer@redhat.com>
    Signed-off-by: Jens Axboe <axboe@fb.com>

commit 174fd8d369613c4e06660f3704caaba48dac8554
Author: Tejun Heo <tj@kernel.org>
Date:   Thu Oct 22 09:27:12 2015 +0900

    blkcg: fix incorrect read/write sync/async stat accounting
    
    While unifying how blkcg stats are collected, 77ea733884eb ("blkcg:
    move io_service_bytes and io_serviced stats into blkcg_gq")
    incorrectly used bio->flags instead of bio->rw to tell the IO type.
    This made IOs to be accounted as the wrong type.  Fix it.
    
    Signed-off-by: Tejun Heo <tj@kernel.org>
    Fixes: 77ea733884eb ("blkcg: move io_service_bytes and io_serviced stats into blkcg_gq")
    Reviewed-by: Jeff Moyer <jmoyer@redhat.com>
    Signed-off-by: Jens Axboe <axboe@fb.com>

commit 8bce6d35b308d73cdb2ee273c95d711a55be688c
Author: NeilBrown <neilb@suse.com>
Date:   Thu Oct 22 13:20:15 2015 +1100

    md/raid10: fix the 'new' raid10 layout to work correctly.
    
    In Linux 3.9 we introduce a new 'far' layout for RAID10 which was
    supposed to rotate the replicas differently and so provide better
    resilience.  In particular it could survive more combinations of 2
    drive failures.
    
    Unfortunately. due to a coding error, this some did what was wanted,
    sometimes improved less than we hoped, and sometimes - in very
    unlikely circumstances - put multiple replicas on the same device so
    the redundancy was harmed.
    
    No public user-space tool has created arrays using this layout so it
    is very unlikely that zero-redundancy arrays actually exist.  Probably
    no arrays using any form of the new layout exist.  But we cannot be
    certain.
    
    So use another bit in the 'layout' number and introduce a bug-fixed
    version of the layout.
    Also when assembling an array, if it has a zero-redundancy layout,
    give a warning.
    
    Reported-by: Heinz Mauelshagen <heinzm@redhat.com>
    Signed-off-by: NeilBrown <neilb@suse.com>

commit c340702ca26a628832fade4f133d8160a55c29cc
Author: NeilBrown <neilb@suse.com>
Date:   Sat Oct 24 16:23:48 2015 +1100

    md/raid10: don't clear bitmap bit when bad-block-list write fails.
    
    When a write fails and a bad-block-list is present, we can
    update the bad-block-list instead of writing the data.  If
    this succeeds then it is OK clear the relevant bitmap-bit as
    no further 'sync' of the block is needed.
    
    However if writing the bad-block-list fails then we need to
    treat the write as failed and particularly must not clear
    the bitmap bit.  Otherwise the device can be re-added (after
    any hardware connection issues are resolved) and because the
    relevant bit in the bitmap is clear, that block will not be
    resynced.  This leads to data corruption.
    
    We already delay the final bio_endio() on the write until
    the bad-block-list is written so that when the write
    returns: either that data is safe, the bad-block record is
    safe, or the fact that the device is faulty is safe.
    However we *don't* delay the clearing of the bitmap, so the
    bitmap bit can be recorded as cleared before we know if the
    bad-block-list was written safely.
    
    So: delay that until the write really is safe.
    i.e. move the call to close_write() until just before
    calling bio_endio(), and recheck the 'is array degraded'
    status before making that call.
    
    This bug goes back to v3.1 when bad-block-lists were
    introduced, though it only affects arrays created with
    mdadm-3.3 or later as only those have bad-block lists.
    
    Backports will require at least
    Commit: 95af587e95aa ("md/raid10: ensure device failure recorded before write request returns.")
    as well.  I'll send that to 'stable' separately.
    
    Note that of the two tests of R10BIO_WriteError that this
    patch adds, the first is certain to fail and the second is
    certain to succeed.  However doing it this way makes the
    patch more obviously correct.  I will tidy the code up in a
    future merge window.
    
    Reported-by: Nate Dailey <nate.dailey@stratus.com>
    Fixes: bd870a16c594 ("md/raid10:  Handle write errors by updating badblock log.")
    Signed-off-by: NeilBrown <neilb@suse.com>

commit bd8688a199b864944bf62eebed0ca13b46249453
Author: NeilBrown <neilb@suse.com>
Date:   Sat Oct 24 16:02:16 2015 +1100

    md/raid1: don't clear bitmap bit when bad-block-list write fails.
    
    When a write fails and a bad-block-list is present, we can
    update the bad-block-list instead of writing the data.  If
    this succeeds then it is OK clear the relevant bitmap-bit as
    no further 'sync' of the block is needed.
    
    However if writing the bad-block-list fails then we need to
    treat the write as failed and particularly must not clear
    the bitmap bit.  Otherwise the device can be re-added (after
    any hardware connection issues are resolved) and because the
    relevant bit in the bitmap is clear, that block will not be
    resynced.  This leads to data corruption.
    
    We already delay the final bio_endio() on the write until
    the bad-block-list is written so that when the write
    returns: either that data is safe, the bad-block record is
    safe, or the fact that the device is faulty is safe.
    However we *don't* delay the clearing of the bitmap, so the
    bitmap bit can be recorded as cleared before we know if the
    bad-block-list was written safely.
    
    So: delay that until the write really is safe.
    i.e. move the call to close_write() until just before
    calling bio_endio(), and recheck the 'is array degraded'
    status before making that call.
    
    This bug goes back to v3.1 when bad-block-lists were
    introduced, though it only affects arrays created with
    mdadm-3.3 or later as only those have bad-block lists.
    
    Backports will require at least
    Commit: 55ce74d4bfe1 ("md/raid1: ensure device failure recorded before write request returns.")
    as well.  I'll send that to 'stable' separately.
    
    Note that of the two tests of R1BIO_WriteError that this
    patch adds, the first is certain to fail and the second is
    certain to succeed.  However doing it this way makes the
    patch more obviously correct.  I will tidy the code up in a
    future merge window.
    
    Reported-and-tested-by: Nate Dailey <nate.dailey@stratus.com>
    Cc: Jes Sorensen <Jes.Sorensen@redhat.com>
    Fixes: cd5ff9a16f08 ("md/raid1:  Handle write errors by updating badblock log.")
    Signed-off-by: NeilBrown <neilb@suse.com>

commit 5dd32eae604ee503e5a84a4f18d1381e4cc356cb
Author: Vladimir Zapolskiy <vz@mleia.com>
Date:   Sat Oct 17 21:52:27 2015 +0300

    i2c: pnx: fix runtime warnings caused by enabling unprepared clock
    
    The driver can not be used on a platform with common clock framework
    until clk_prepare/clk_unprepare calls are added, otherwise clk_enable
    calls will fail and a WARN is generated.
    
    Signed-off-by: Vladimir Zapolskiy <vz@mleia.com>
    Signed-off-by: Wolfram Sang <wsa@the-dreams.de>

commit c86f5ebfbd147d1a228ab89ee1658e18939bd7ad
Author: Alex Deucher <alexander.deucher@amd.com>
Date:   Fri Oct 23 10:45:14 2015 -0400

    drm/amdgpu: don't try to recreate sysfs entries on resume
    
    Fixes an error on resume caused by:
    fa022a9b65d2886486a022fd66b20c823cd76ad9
    
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Cc: stable@vger.kernel.org

commit 49abb26651167c892393cd9f2ad23df429645ed9
Author: Alex Deucher <alexander.deucher@amd.com>
Date:   Fri Oct 23 10:38:52 2015 -0400

    drm/radeon: don't try to recreate sysfs entries on resume
    
    Fixes a harmless error message caused by:
    51a4726b04e880fdd9b4e0e58b13f70b0a68a7f5
    
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
    Cc: stable@vger.kernel.org

commit 5c92d87d30b23844e6998d8318e4c19ee3a907ac
Author: Christian König <christian.koenig@amd.com>
Date:   Wed Oct 21 21:58:28 2015 +0200

    drm/amdgpu: stop leaking page flip fence
    
    reservation_object_get_fences_rcu already takes the references.
    
    Signed-off-by: Christian König <christian.koenig@amd.com>
    Reviewed-by: Alex Deucher <alexander.deucher@amd.com>
    Reviewed-by: Chunming Zhou <david1.zhou@amd.com>
    Reviewed-by: Jammy Zhou <Jammy.Zhou@amd.com>

commit 0729a04977d497cf66234fd7f900ddcec3ef1c52
Author: Hezi Shahmoon <hezi@marvell.com>
Date:   Tue Oct 20 16:32:24 2015 +0200

    i2c: mv64xxx: really allow I2C offloading
    
    Commit 00d8689b85a7 ("i2c: mv64xxx: rework offload support to fix
    several problems") completely reworked the offload support, but left a
    debugging-related "return false" at the beginning of the
    mv64xxx_i2c_can_offload() function. This has the unfortunate consequence
    that offloading is in fact never used, which wasn't really the
    intention.
    
    This commit fixes that problem by removing the bogus "return false".
    
    Fixes: 00d8689b85a7 ("i2c: mv64xxx: rework offload support to fix several problems")
    Signed-off-by: Hezi Shahmoon <hezi@marvell.com>
    [Thomas: reworked commit log and title.]
    Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
    Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
    Cc: <stable@vger.kernel.org>

commit 09dc1387c9c06cdaf55bc99b35238bd2ec0aed4b
Author: Thomas Hellstrom <thellstrom@vmware.com>
Date:   Wed Oct 21 21:31:49 2015 +0200

    drm/vmwgfx: Stabilize the command buffer submission code
    
    This commit addresses some stability problems with the command buffer
    submission code recently introduced:
    
    1) Make the vmw_cmdbuf_man_process() function handle reruns internally to
    avoid losing interrupts if the caller forgets to rerun on -EAGAIN.
    2) Handle default command buffer allocations using inline command buffers.
    This avoids rare allocation deadlocks.
    3) In case of command buffer errors we might lose fence submissions.
    Therefore send a new fence after each command buffer error. This will help
    avoid lengthy fence waits.
    
    Signed-off-by: Thomas Hellstrom <thellstrom@vmware.com>
    Reviewed-by: Sinclair Yeh <syeh@vmware.com>

commit cbf3ccd09d683abf1cacd36e3640872ee912d99b
Author: Joerg Roedel <jroedel@suse.de>
Date:   Tue Oct 20 14:59:36 2015 +0200

    iommu/amd: Don't clear DTE flags when modifying it
    
    During device assignment/deassignment the flags in the DTE
    get lost, which might cause spurious faults, for example
    when the device tries to access the system management range.
    Fix this by not clearing the flags with the rest of the DTE.
    
    Reported-by: G. Richard Bellamy <rbellamy@pteradigm.com>
    Tested-by: G. Richard Bellamy <rbellamy@pteradigm.com>
    Cc: stable@vger.kernel.org
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

commit 681ab4696062f5aa939c9e04d058732306a97176
Author: Jes Sorensen <Jes.Sorensen@redhat.com>
Date:   Tue Oct 20 12:09:13 2015 -0400

    md/raid10: submit_bio_wait() returns 0 on success
    
    This was introduced with 9e882242c6193ae6f416f2d8d8db0d9126bd996b
    which changed the return value of submit_bio_wait() to return != 0 on
    error, but didn't update the caller accordingly.
    
    Fixes: 9e882242c6 ("block: Add submit_bio_wait(), remove from md")
    Cc: stable@vger.kernel.org (v3.10)
    Reported-by: Bill Kuzeja <William.Kuzeja@stratus.com>
    Signed-off-by: Jes Sorensen <Jes.Sorensen@redhat.com>
    Signed-off-by: NeilBrown <neilb@suse.com>

commit 203d27b0226a05202438ddb39ef0ef1acb14a759
Author: Jes Sorensen <Jes.Sorensen@redhat.com>
Date:   Tue Oct 20 12:09:12 2015 -0400

    md/raid1: submit_bio_wait() returns 0 on success
    
    This was introduced with 9e882242c6193ae6f416f2d8d8db0d9126bd996b
    which changed the return value of submit_bio_wait() to return != 0 on
    error, but didn't update the caller accordingly.
    
    Fixes: 9e882242c6 ("block: Add submit_bio_wait(), remove from md")
    Cc: stable@vger.kernel.org (v3.10)
    Reported-by: Bill Kuzeja <William.Kuzeja@stratus.com>
    Signed-off-by: Jes Sorensen <Jes.Sorensen@redhat.com>
    Signed-off-by: NeilBrown <neilb@suse.com>

commit 625faa6a720d26fc0db9e20b48dc0dfe4c8d8ddf
Author: Russell King <rmk+kernel@arm.linux.org.uk>
Date:   Tue Oct 20 11:49:44 2015 +0100

    clkdev: fix clk_add_alias() with a NULL alias device name
    
    clk_add_alias() was not correctly handling the case where alias_dev_name
    was NULL: rather than producing an entry with a NULL dev_id pointer,
    it would produce a device name of (null).  Fix this.
    
    Cc: <stable@vger.kernel.org>
    Fixes: 2568999835d7 ("clkdev: add clkdev_create() helper")
    Reported-by: Aaro Koskinen <aaro.koskinen@iki.fi>
    Tested-by: Aaro Koskinen <aaro.koskinen@iki.fi>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 3fc89adb9fa4beff31374a4bf50b3d099d88ae83
Author: Herbert Xu <herbert@gondor.apana.org.au>
Date:   Mon Oct 19 18:23:57 2015 +0800

    crypto: api - Only abort operations on fatal signal
    
    Currently a number of Crypto API operations may fail when a signal
    occurs.  This causes nasty problems as the caller of those operations
    are often not in a good position to restart the operation.
    
    In fact there is currently no need for those operations to be
    interrupted by user signals at all.  All we need is for them to
    be killable.
    
    This patch replaces the relevant calls of signal_pending with
    fatal_signal_pending, and wait_for_completion_interruptible with
    wait_for_completion_killable, respectively.
    
    Cc: stable@vger.kernel.org
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit 8a603f91cc4848ab1a0458bc065aa9f64322e123
Author: H. Nikolaus Schaller <hns@goldelico.com>
Date:   Fri Oct 16 22:19:06 2015 +0100

    ARM: 8445/1: fix vdsomunge not to depend on glibc specific byteswap.h
    
    If the host toolchain is not glibc based then the arm kernel build
    fails with
    
      HOSTCC  arch/arm/vdso/vdsomunge
      arch/arm/vdso/vdsomunge.c:48:22: fatal error: byteswap.h: No such file or directory
    
    Observed: with omap2plus_defconfig and compile on Mac OS X with arm ELF
    cross-compiler.
    
    Reason: byteswap.h is a glibc only header.
    
    Solution: replace by private byte-swapping macros (taken from
    arch/mips/boot/elf2ecoff.c and kindly improved by Russell King)
    
    Tested to compile on Mac OS X 10.9.5 host.
    
    Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>
    Signed-off-by: Nathan Lynch <nathan_lynch@mentor.com>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit d14f6fced5f9360edca5a1325ddb7077aab1203b
Author: Jay Cornwall <jay@jcornwall.me>
Date:   Wed Sep 16 14:10:03 2015 -0500

    iommu/amd: Fix BUG when faulting a PROT_NONE VMA
    
    handle_mm_fault indirectly triggers a BUG in do_numa_page
    when given a VMA without read/write/execute access. Check
    this condition in do_fault.
    
    do_fault -> handle_mm_fault -> handle_pte_fault -> do_numa_page
    
      mm/memory.c
      3147  static int do_numa_page(struct mm_struct *mm, struct vm_area_struct *vma,
      ....
      3159  /* A PROT_NONE fault should not end up here */
      3160  BUG_ON(!(vma->vm_flags & (VM_READ | VM_EXEC | VM_WRITE)));
    
    Signed-off-by: Jay Cornwall <jay@jcornwall.me>
    Cc: <stable@vger.kernel.org> # v4.1+
    Signed-off-by: Joerg Roedel <jroedel@suse.de>

commit 868e87ccda2461cafd4a0d39f1486eb8f4a9a6f9
Author: Russell King <rmk+kernel@arm.linux.org.uk>
Date:   Mon Sep 28 10:31:50 2015 +0100

    ARM: make RiscPC depend on MMU
    
    RiscPC fails to build if MMU is disabled:
    
    arch/arm/mach-rpc/ecard.c: In function 'ecard_init_pgtables':
    arch/arm/mach-rpc/ecard.c:229:2: error: implicit declaration of function 'pgd_offset' [-Werror=implicit-function-declaration]
    
    arrange for RiscPC to depend on MMU.
    
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 275d7d44d802ef271a42dc87ac091a495ba72fc5
Author: Peter Zijlstra <peterz@infradead.org>
Date:   Thu Aug 20 10:34:59 2015 +0930

    module: Fix locking in symbol_put_addr()
    
    Poma (on the way to another bug) reported an assertion triggering:
    
      [<ffffffff81150529>] module_assert_mutex_or_preempt+0x49/0x90
      [<ffffffff81150822>] __module_address+0x32/0x150
      [<ffffffff81150956>] __module_text_address+0x16/0x70
      [<ffffffff81150f19>] symbol_put_addr+0x29/0x40
      [<ffffffffa04b77ad>] dvb_frontend_detach+0x7d/0x90 [dvb_core]
    
    Laura Abbott <labbott@redhat.com> produced a patch which lead us to
    inspect symbol_put_addr(). This function has a comment claiming it
    doesn't need to disable preemption around the module lookup
    because it holds a reference to the module it wants to find, which
    therefore cannot go away.
    
    This is wrong (and a false optimization too, preempt_disable() is really
    rather cheap, and I doubt any of this is on uber critical paths,
    otherwise it would've retained a pointer to the actual module anyway and
    avoided the second lookup).
    
    While its true that the module cannot go away while we hold a reference
    on it, the data structure we do the lookup in very much _CAN_ change
    while we do the lookup. Therefore fix the comment and add the
    required preempt_disable().
    
    Reported-by: poma <pomidorabelisima@gmail.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
    Fixes: a6e6abd575fc ("module: remove module_text_address()")
    Cc: stable@kernel.org
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>