support-resetting-warn_once-checkpatch-fixes
ERROR: code indent should use tabs where possible
#124: FILE: kernel/panic.c:604:
+                        clear_warn_once_set,$

WARNING: please, no spaces at the start of a line
#124: FILE: kernel/panic.c:604:
+                        clear_warn_once_set,$

ERROR: code indent should use tabs where possible
#125: FILE: kernel/panic.c:605:
+^I^I        "%lld\n");$

WARNING: please use device_initcall() or more appropriate function instead of __initcall() (see include/linux/init.h)
#135: FILE: kernel/panic.c:615:
+__initcall(register_warn_debugfs);

total: 2 errors, 2 warnings, 87 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/support-resetting-warn_once.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Andi Kleen <ak@linux.intel.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>