sysvipc-unteach-ids-next_id-for-checkpoint_restore-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#14: 
03f595668017f ("ipc: add sysctl to specify desired next object id"). 

WARNING: macros should not use a trailing semicolon
#75: FILE: ipc/util.c:224:
+#define ipc_idr_alloc(ids, new)						\
+	idr_alloc(&(ids)->ipcs_idr, (new),				\
+		  (ids)->next_id < 0 ? 0: ipcid_to_idx((ids)->next_id), \
+		  0, GFP_NOWAIT);

ERROR: spaces required around that ':' (ctx:VxW)
#77: FILE: ipc/util.c:226:
+		  (ids)->next_id < 0 ? 0: ipcid_to_idx((ids)->next_id), \
 		                        ^

WARNING: macros should not use a trailing semicolon
#96: FILE: ipc/util.c:245:
+#define ipc_idr_alloc(ids, new)					\
+	idr_alloc(&(ids)->ipcs_idr, (new), 0, 0, GFP_NOWAIT);

total: 2 errors, 2 warnings, 117 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/sysvipc-unteach-ids-next_id-for-checkpoint_restore.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Davidlohr Bueso <dave@stgolabs.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>