origin
GIT d25ed277fbd4c20247286fda2014ae6a2b88316b

commit eda2116f4ab6d79cfcffc202b5d2bbb0797ba013
Author: Steve French <smfrench@gmail.com>
Date:   Fri Sep 11 19:24:19 2015 -0500

    [CIFS] mount option sec=none not displayed properly in /proc/mounts
    
    When the user specifies "sec=none" in a cifs mount, we set
    sec_type as unspecified (and set a flag and the username will be
    null) rather than setting sectype as "none" so
    cifs_show_security was not properly displaying it in
    cifs /proc/mounts entries.
    
    Signed-off-by: Steve French <steve.french@primarydata.com>
    Reviewed-by: Jeff Layton <jlayton@poochiereds.net>

commit a4a5a7379e4ca03c192b732d61e446994eb67bbc
Author: Robert Jarzmik <robert.jarzmik@free.fr>
Date:   Fri Sep 11 17:12:27 2015 +0100

    ARM: 8431/1: fix alignement of __bug_table section entries
    
    On old ARM chips, unaligned accesses to memory are not trapped and
    fixed.  On module load, symbols are relocated, and the relocation of
    __bug_table symbols is done on a u32 basis. Yet the section is not
    aligned to a multiple of 4 address, but to a multiple of 2.
    
    This triggers an Oops on pxa architecture, where address 0xbf0021ea
    is the first relocation in the __bug_table section :
      apply_relocate(): pxa3xx_nand: section 13 reloc 0 sym ''
      Unable to handle kernel paging request at virtual address bf0021ea
      pgd = e1cd0000
      [bf0021ea] *pgd=c1cce851, *pte=c1cde04f, *ppte=c1cde01f
      Internal error: Oops: 23 [#1] ARM
      Modules linked in:
      CPU: 0 PID: 606 Comm: insmod Not tainted 4.2.0-rc8-next-20150828-cm-x300+ #887
      Hardware name: CM-X300 module
      task: e1c68700 ti: e1c3e000 task.ti: e1c3e000
      PC is at apply_relocate+0x2f4/0x3d4
      LR is at 0xbf0021ea
      pc : [<c000e7c8>]    lr : [<bf0021ea>]    psr: 80000013
      sp : e1c3fe30  ip : 60000013  fp : e49e8c60
      r10: e49e8fa8  r9 : 00000000  r8 : e49e7c58
      r7 : e49e8c38  r6 : e49e8a58  r5 : e49e8920  r4 : e49e8918
      r3 : bf0021ea  r2 : bf007034  r1 : 00000000  r0 : bf000000
      Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
      Control: 0000397f  Table: c1cd0018  DAC: 00000051
      Process insmod (pid: 606, stack limit = 0xe1c3e198)
      [<c000e7c8>] (apply_relocate) from [<c005ce5c>] (load_module+0x1248/0x1f5c)
      [<c005ce5c>] (load_module) from [<c005dc54>] (SyS_init_module+0xe4/0x170)
      [<c005dc54>] (SyS_init_module) from [<c000a420>] (ret_fast_syscall+0x0/0x38)
    
    Fix this by ensuring entries in __bug_table are all aligned to at least
    of multiple of 4. This transforms a module section  __bug_table as :
    -   [12] __bug_table       PROGBITS        00000000 002232 000018 00   A  0   0  1
    +   [12] __bug_table       PROGBITS        00000000 002232 000018 00   A  0   0  4
    
    Signed-off-by: Robert Jarzmik <robert.jarzmik@free.fr>
    Reviewed-by: Dave Martin <Dave.Martin@arm.com>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 0b61f2c0f37983c98ed4207f3f5e265938371b68
Author: Julien Grall <julien.grall@citrix.com>
Date:   Fri Sep 11 17:25:59 2015 +0100

    arm/xen: Enable user access to the kernel before issuing a privcmd call
    
    When Xen is copying data to/from the guest it will check if the kernel
    has the right to do the access. If not, the hypercall will return an
    error.
    
    After the commit a5e090acbf545c0a3b04080f8a488b17ec41fe02 "ARM:
    software-based privileged-no-access support", the kernel can't access
    any longer the user space by default. This will result to fail on every
    hypercall made by the userspace (i.e via privcmd).
    
    We have to enable the userspace access and then restore the correct
    permission every time the privcmd is used to made an hypercall.
    
    I didn't find generic helpers to do a these operations, so the change
    is only arm32 specific.
    
    Reported-by: Riku Voipio <riku.voipio@linaro.org>
    Signed-off-by: Julien Grall <julien.grall@citrix.com>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 6e8f580d1fcc18e290713984c379cb97131c015a
Author: Russell King <rmk+kernel@arm.linux.org.uk>
Date:   Fri Sep 11 08:34:52 2015 +0100

    ARM: domains: add memory dependencies to get_domain/set_domain
    
    We need to have memory dependencies on get_domain/set_domain to avoid
    the compiler over-optimising these inline assembly instructions.
    
    Loads/stores must not be reordered across a set_domain(), so introduce
    a compiler barrier for that assembly.
    
    The value of get_domain() must not be cached across a set_domain(), but
    we still want to allow the compiler to optimise it away.  Introduce a
    dependency on current_thread_info()->cpu_domain to avoid this; the new
    memory clobber in set_domain() should therefore cause the compiler to
    re-load this.  The other advantage of using this is we should have its
    address in the register set already, or very soon after at most call
    sites.
    
    Tested-by: Robert Jarzmik <robert.jarzmik@free.fr>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 716ff1921a86c637b8875c7bb312fc6755fa9300
Author: Russell King <rmk+kernel@arm.linux.org.uk>
Date:   Fri Sep 11 08:17:39 2015 +0100

    ARM: domains: thread_info.h no longer needs asm/domains.h
    
    As of 1eef5d2f1b46 ("ARM: domains: switch to keeping domain value in
    register") we no longer need to include asm/domains.h into
    asm/thread_info.h.  Remove it.
    
    Tested-by: Robert Jarzmik <robert.jarzmik@free.fr>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 4c17a6d56bb0cad3066a714e94f7185a24b40f49
Author: Jann Horn <jann@thejh.net>
Date:   Fri Sep 11 16:27:27 2015 +0200

    CIFS: fix type confusion in copy offload ioctl
    
    This might lead to local privilege escalation (code execution as
    kernel) for systems where the following conditions are met:
    
     - CONFIG_CIFS_SMB2 and CONFIG_CIFS_POSIX are enabled
     - a cifs filesystem is mounted where:
      - the mount option "vers" was used and set to a value >=2.0
      - the attacker has write access to at least one file on the filesystem
    
    To attack this, an attacker would have to guess the target_tcon
    pointer (but guessing wrong doesn't cause a crash, it just returns an
    error code) and win a narrow race.
    
    CC: Stable <stable@vger.kernel.org>
    Signed-off-by: Jann Horn <jann@thejh.net>
    Signed-off-by: Steve French <smfrench@gmail.com>

commit 3bba75a2ec32bd5fa7024a4de3b8cf9ee113a76a
Author: Romain Perier <romain.perier@gmail.com>
Date:   Sun Aug 23 11:32:37 2015 +0200

    clk: rockchip: Add pclk_peri to critical clocks on RK3066/RK3188
    
    Now that the rockchip clock subsystem does clock gating with GPIO banks,
    these are no longer enabled once during probe and no longer stay enabled
    for eternity. When all these clocks are disabled, the parent clock pclk_peri
    might be disabled too, as no other child claims it. So, we need to add pclk_peri
    to the critical clocks.
    
    Signed-off-by: Romain Perier <romain.perier@gmail.com>
    Tested-by: Michael Niewoehner <linux@mniewoehner.de>
    Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>

commit 1166160ab531198f7abc773992c0e04d0f9b7600
Author: Michael Niewoehner <linux@mniewoehner.de>
Date:   Tue Aug 25 22:22:07 2015 +0200

    clk: rockchip: add pclk_cpu to the list of rk3188 critical clocks
    
    pclk_cpu needs to keep running because it is needed for devices like
    the act8865 regulator but with the recent gpio clock handling this is
    not always the case anymore. So add it to the list of critical clocks.
    
    Signed-off-by: Michael Niewoehner <linux@mniewoehner.de>
    Reviewed-by: Heiko Stuebner <heiko@sntech.de>
    Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>

commit bb0f73616396e7929b68d3bdea70064003599d33
Author: Heiko Stuebner <heiko@sntech.de>
Date:   Fri Aug 21 19:51:41 2015 +0200

    clk: rockchip: handle critical clocks after registering all clocks
    
    Currently the registration of critical clocks is done in the function
    shared between rk3066 and rk3188 clock trees. That results in them
    getting handled maybe before all of them are registered.
    
    Therefore move the critical clock handling down to the end of the soc-
    specific clock registration function, so that all clocks are registered
    before they're maybe handled as critical clock.
    
    Signed-off-by: Heiko Stuebner <heiko@sntech.de>
    Tested-by: Michael Niewoehner <linux@mniewoehner.de>
    Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>

commit af4cb25df93d2e7a97d65db2bfacaa4400988dea
Author: Russell King <rmk+kernel@arm.linux.org.uk>
Date:   Wed Sep 9 21:19:49 2015 +0100

    ARM: uaccess: fix undefined instruction on ARMv7M/noMMU
    
    The use of get_domain() in copy_thread() results in an oops on
    ARMv7M/noMMU systems.  The thread cpu_domain value is only used when
    CONFIG_CPU_USE_DOMAINS is enabled, so there's no need to save the
    value in copy_thread() except when this is enabled, and this option
    will never be enabled on these platforms.
    
    Unhandled exception: IPSR = 00000006 LR = fffffff1
    CPU: 0 PID: 0 Comm: swapper Not tainted 4.2.0-next-20150909-00001-gb8ec5ad #41
    Hardware name: NXP LPC18xx/43xx (Device Tree)
    task: 2823fbe0 ti: 2823c000 task.ti: 2823c000
    PC is at copy_thread+0x18/0x92
    LR is at copy_thread+0x19/0x92
    pc : [<2800a46e>]    lr : [<2800a46f>]    psr: 4100000b
    sp : 2823df00  ip : 00000000  fp : 287c81c0
    r10: 00000000  r9 : 00800300  r8 : 287c8000
    r7 : 287c8000  r6 : 2818908d  r5 : 00000000  r4 : 287ca000
    r3 : 00000000  r2 : 00000000  r1 : fffffff0  r0 : 287ca048
    xPSR: 4100000b
    
    Reported-by: Ariel D'Alessandro <ariel@vanguardiasur.com.ar>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 296254f3223d201f2aa53f5f717eedfdc63f3db8
Author: Russell King <rmk+kernel@arm.linux.org.uk>
Date:   Mon Sep 7 00:30:06 2015 +0100

    ARM: uaccess: remove unneeded uaccess_save_and_disable macro
    
    This macro is never referenced, remove it.
    
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 39dc53deff30d9b239ac36cfeb0ef2022d03a449
Author: Russell King <rmk+kernel@arm.linux.org.uk>
Date:   Mon Sep 7 00:29:15 2015 +0100

    ARM: swpan: fix nwfpe for uaccess changes
    
    NWFPE needs to access userspace to check whether the next instruction
    is another FP instruction.  Allow userspace access for this read.
    
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit a077224fd35b2f7fbc93f14cf67074fc792fbac2
Author: Ard Biesheuvel <ard.biesheuvel@linaro.org>
Date:   Thu Sep 3 13:24:40 2015 +0100

    ARM: 8429/1: disable GCC SRA optimization
    
    While working on the 32-bit ARM port of UEFI, I noticed a strange
    corruption in the kernel log. The following snprintf() statement
    (in drivers/firmware/efi/efi.c:efi_md_typeattr_format())
    
    	snprintf(pos, size, "|%3s|%2s|%2s|%2s|%3s|%2s|%2s|%2s|%2s]",
    
    was producing the following output in the log:
    
    	|    |   |   |   |    |WB|WT|WC|UC]
    	|    |   |   |   |    |WB|WT|WC|UC]
    	|    |   |   |   |    |WB|WT|WC|UC]
    	|RUN|   |   |   |    |WB|WT|WC|UC]*
    	|RUN|   |   |   |    |WB|WT|WC|UC]*
    	|    |   |   |   |    |WB|WT|WC|UC]
    	|RUN|   |   |   |    |WB|WT|WC|UC]*
    	|    |   |   |   |    |WB|WT|WC|UC]
    	|RUN|   |   |   |    |   |   |   |UC]
    	|RUN|   |   |   |    |   |   |   |UC]
    
    As it turns out, this is caused by incorrect code being emitted for
    the string() function in lib/vsprintf.c. The following code
    
    	if (!(spec.flags & LEFT)) {
    		while (len < spec.field_width--) {
    			if (buf < end)
    				*buf = ' ';
    			++buf;
    		}
    	}
    	for (i = 0; i < len; ++i) {
    		if (buf < end)
    			*buf = *s;
    		++buf; ++s;
    	}
    	while (len < spec.field_width--) {
    		if (buf < end)
    			*buf = ' ';
    		++buf;
    	}
    
    when called with len == 0, triggers an issue in the GCC SRA optimization
    pass (Scalar Replacement of Aggregates), which handles promotion of signed
    struct members incorrectly. This is a known but as yet unresolved issue.
    (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65932). In this particular
    case, it is causing the second while loop to be executed erroneously a
    single time, causing the additional space characters to be printed.
    
    So disable the optimization by passing -fno-ipa-sra.
    
    Cc: <stable@vger.kernel.org>
    Acked-by: Nicolas Pitre <nico@linaro.org>
    Signed-off-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>
    Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>

commit 9f42a89da6b4dc015631e01ba990d3db2cae2a1b
Author: Leo Yan <leo.yan@linaro.org>
Date:   Wed Sep 2 10:57:47 2015 +0800

    clk: Hi6220: separately build stub clock driver
    
    The previous code, kernel builds Hi6220's common clock driver and stub
    clock driver together. Stub clock driver has introduced the dependency
    with CONFIG_MAILBOX, so kernel will not build Hi6220's common clock
    driver due ARM64's defconfig have not enabled CONFIG_MAILBOX by default.
    
    So separately build stub clock driver and common clock driver for
    Hi6220; and only let stub clock driver has the dependency with
    CONFIG_MAILBOX.
    
    Signed-off-by: Leo Yan <leo.yan@linaro.org>
    Tested-by: Kevin Hilman <khilman@linaro.org>
    Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>

commit ac0e137ab0da80e8fc0db2027598e2f7f82a5a02
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Mon Aug 31 20:27:32 2015 -0700

    clk: h8s2678: Fix compile error
    
    Recent cleanup removed some include files without checking if the cleaned
    up code still compiles. This results in the following compile error.
    
    drivers/clk/h8300/clk-h8s2678.c: In function ‘h8s2678_pll_clk_setup’:
    drivers/clk/h8300/clk-h8s2678.c:99:14: error:
    	implicit declaration of function ‘kzalloc’
    drivers/clk/h8300/clk-h8s2678.c:138:2: error:
          implicit declaration of function ‘kfree’
    
    Cc: Yoshinori Sato <ysato@users.sourceforge.jp>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>