kasan: add declarations for internal functions
A patch got merged that made newly added functions static, leading
to a warning about unused functions as well as a link error when
they are actually used:

mm/kasan/kasan.c:780:7: error: '__asan_set_shadow_f8' defined but not used [-Werror=unused-function]
mm/kasan/kasan.c:791:8: note: in expansion of macro 'DEFINE_ASAN_SET_SHADOW'
mm/kasan/kasan.c:780:7: error: '__asan_set_shadow_f5' defined but not used [-Werror=unused-function]

It turns out the underlying problem is that a lot of the internal
interfaces of the kasan implementation are only ever called from
code generated by the compiler. These don't need any declarations
to work fine, but cause warnings both with sparse and with 'make W=1':

mm/kasan/kasan.c:695:1: warning: symbol '__asan_load1' was not declared. Should it be static?
mm/kasan/kasan.c:695:1: warning: symbol '__asan_store1' was not declared. Should it be static?
mm/kasan/kasan.c:696:1: warning: symbol '__asan_load2' was not declared. Should it be static?
mm/kasan/kasan.c:696:1: warning: symbol '__asan_store2' was not declared. Should it be static?
mm/kasan/kasan.c:697:1: warning: symbol '__asan_load4' was not declared. Should it be static?

This removes the bogus 'static' annotation and adds declarations
for all affected interfaces.

Link: http://lkml.kernel.org/r/20180105094112.2690475-1-arnd@arndb.de
Fixes: mmotm ("kasan: __asan_set_shadow_00 can be static")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Dmitry Vyukov <dvyukov@google.com>
Cc: Alexander Potapenko <glider@google.com>
Cc: Greg Hackmann <ghackmann@google.com>
Cc: Paul Lawrence <paullawrence@google.com>
Cc: Andrey Ryabinin <aryabinin@virtuozzo.com>
Cc: Masahiro Yamada <yamada.masahiro@socionext.com>
Cc: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>