origin
GIT 8ba4caf1ee1585f018d32ab924244c9589bc9f37

commit 8ba4caf1ee1585f018d32ab924244c9589bc9f37
Author: Paul Gortmaker <paul.gortmaker@windriver.com>
Date:   Wed Sep 17 10:57:45 2014 -0400

    Revert "init: make rootdelay=N consistent with rootwait behaviour"
    
    This reverts commit 4dfe694f616e00e6fd83e5bbcd7a3c4d7113493d.
    
    In that, we did:
    
      Here we move the rootdelay code to be right beside the rootwait code, so
      that their behaviour is consistent.
    
    ...which is fine, but in hindsight, perhaps moving the rootwait to be
    beside the rootdelay would have been better.  We also indicated:
    
      It should be noted that in doing so, the actions based on the
      saved_root_name[0] and initrd_load() were previously put on hold by
      rootdelay=N and now currently will not be delayed.  However, I think
      consistent behaviour is more important than matching historical behaviour
      of delaying the above two operations.
    
    But Pavel reported an instance where an ARM target with root on MMC
    was failing to mount root, and Russell diagnosed it to the fact that
    the call to set ROOT_DEV within the saved_root_name[0] processing
    block mentioned above was no longer being delayed.
    
    Rather than moving both wait clauses to the original position of
    rootdelay and risking unearthing other possible corner case breakage
    at this point in time, we simply revert now and we can revisit
    trying the alternate/earlier location in another development cycle.
    
    Cc: Pavel Machek <pavel@denx.de>
    Cc: Russell King <linux@arm.linux.org.uk>
    Cc: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit a060dc5010ffa32f3a83e5336f6eeb6551fa137a
Author: James Hogan <james.hogan@imgtec.com>
Date:   Tue Sep 16 13:07:35 2014 +0100

    vfs: workaround gcc <4.6 build error in link_path_walk()
    
    Commit d6bb3e9075bb ("vfs: simplify and shrink stack frame of
    link_path_walk()") introduced build problems with GCC versions older
    than 4.6 due to the initialisation of a member of an anonymous union in
    struct qstr without enclosing braces.
    
    This hits GCC bug 10676 [1] (which was fixed in GCC 4.6 by [2]), and
    causes the following build error:
    
      fs/namei.c: In function 'link_path_walk':
      fs/namei.c:1778: error: unknown field 'hash_len' specified in initializer
    
    This is worked around by adding explicit braces.
    
    [1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=10676
    [2] https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=159206
    
    Fixes: d6bb3e9075bb (vfs: simplify and shrink stack frame of link_path_walk())
    Signed-off-by: James Hogan <james.hogan@imgtec.com>
    Cc: Linus Torvalds <torvalds@linux-foundation.org>
    Cc: Alexander Viro <viro@zeniv.linux.org.uk>
    Cc: Geert Uytterhoeven <geert@linux-m68k.org>
    Cc: linux-fsdevel@vger.kernel.org
    Cc: linux-metag@vger.kernel.org
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit f3b5933190c1fc5ad8f3a1dec594e9e849e088c0
Author: Tony Luck <tony.luck@intel.com>
Date:   Mon Sep 15 09:32:23 2014 -0700

    ia64: Fix syscall number for memfd_create
    
    Cut & paste typo from the line above.
    
    Reported-by: Ben Hutchings <ben@decadent.org.uk>
    Signed-off-by: Tony Luck <tony.luck@intel.com>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit d6bb3e9075bbcf758d6084bb581f797bb6ea24c6
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Mon Sep 15 10:51:07 2014 -0700

    vfs: simplify and shrink stack frame of link_path_walk()
    
    Commit 9226b5b440f2 ("vfs: avoid non-forwarding large load after small
    store in path lookup") made link_path_walk() always access the
    "hash_len" field as a single 64-bit entity, in order to avoid mixed size
    accesses to the members.
    
    However, what I didn't notice was that that effectively means that the
    whole "struct qstr this" is now basically redundant.  We already
    explicitly track the "const char *name", and if we just use "u64
    hash_len" instead of "long len", there is nothing else left of the
    "struct qstr".
    
    We do end up wanting the "struct qstr" if we have a filesystem with a
    "d_hash()" function, but that's a rare case, and we might as well then
    just squirrell away the name and hash_len at that point.
    
    End result: fewer live variables in the loop, a smaller stack frame, and
    better code generation.  And we don't need to pass in pointers variables
    to helper functions any more, because the return value contains all the
    relevant information.  So this removes more lines than it adds, and the
    source code is clearer too.
    
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit cfb2f9d5c921e38b0f12bb26fed10b877664444d
Author: Al Viro <viro@ZenIV.linux.org.uk>
Date:   Fri Sep 12 20:56:04 2014 +0100

    GFS2: fix d_splice_alias() misuses
    
    Callers of d_splice_alias(dentry, inode) don't need iput(), neither
    on success nor on failure.  Either the reference to inode is stored
    in a previously negative dentry, or it's dropped.  In either case
    inode reference the caller used to hold is consumed.
    
    __gfs2_lookup() does iput() in case when d_splice_alias() has failed.
    Double iput() if we ever hit that.  And gfs2_create_inode() ends up
    not only with double iput(), but with link count dropped to zero - on
    an inode it has just found in directory.
    
    Cc: stable@vger.kernel.org # v3.14+
    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>
    Signed-off-by: Steven Whitehouse <swhiteho@redhat.com>

commit 807362cd960daac415e2c8906750b2472c22c80e
Author: Nick Dyer <nick.dyer@itdev.co.uk>
Date:   Thu Sep 11 10:31:45 2014 -0700

    Input: atmel_mxt_ts - fix merge in DT documentation
    
    Something went a bit wrong in merging f5940231a - there's a bit of repeated
    text that's been introduced.
    
    Signed-off-by: Nick Dyer <nick.dyer@itdev.co.uk>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

commit 266e43c4eb81440e81da6c51bc5d4f9be2b7839c
Author: Hans de Goede <hdegoede@redhat.com>
Date:   Thu Sep 11 10:13:13 2014 -0700

    Input: i8042 - also set the firmware id for MUXed ports
    
    So that firmware-id matching can be used with multiplexed aux ports too.
    
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

commit d2682118f4bb3ceb835f91c1a694407a31bb7378
Author: Hans de Goede <hdegoede@redhat.com>
Date:   Thu Sep 11 10:10:26 2014 -0700

    Input: i8042 - add nomux quirk for Avatar AVIU-145A6
    
    The sys_vendor / product_name are somewhat generic unfortunately, so this
    may lead to some false positives. But nomux usually does no harm, where as
    not having it clearly is causing problems on the Avatar AVIU-145A6.
    
    https://bugzilla.kernel.org/show_bug.cgi?id=77391
    
    Cc: stable@vger.kernel.org
    Reported-by: Hugo P <saurosii@gmail.com>
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

commit cc18a69c92d0972bc2fc5a047ee3be1e8398171b
Author: Hans de Goede <hdegoede@redhat.com>
Date:   Wed Sep 10 13:53:37 2014 -0700

    Input: i8042 - add Fujitsu U574 to no_timeout dmi table
    
    https://bugzilla.kernel.org/show_bug.cgi?id=69731
    
    Cc: stable@vger.kernel.org
    Reported-by: Jason Robinson <mail@jasonrobinson.me>
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

commit c01206796139e2b1feb7539bc72174fef1c6dc6e
Author: Dmitry Torokhov <dmitry.torokhov@gmail.com>
Date:   Wed Sep 10 13:50:37 2014 -0700

    Input: atkbd - do not try 'deactivate' keyboard on any LG laptops
    
    We are getting more and more reports about LG laptops not having
    functioning keyboard if we try to deactivate keyboard during probe.
    Given that having keyboard deactivated is merely "nice to have"
    instead of a hard requirement for probing, let's disable it on all
    LG boxes instead of trying to hunt down particular models.
    
    This change is prompted by patches trying to add "LG Electronics"/"ROCKY"
    and "LG Electronics"/"LW60-F27B" to the DMI list.
    
    https://bugzilla.kernel.org/show_bug.cgi?id=77051
    
    Cc: stable@vger.kernel.org
    Reported-by: Jaime Velasco Juan <jsagarribay@gmail.com>
    Reported-by: Georgios Tsalikis <georgios@tsalikis.net>
    Tested-by: Jaime Velasco Juan <jsagarribay@gmail.com>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>

commit f49819560f53b7f3a596a8ea2e6764dc86695b62
Author: Amos Kong <akong@redhat.com>
Date:   Thu Sep 11 22:21:53 2014 +0930

    virtio-rng: skip reading when we start to remove the device
    
    Before we really unregister the hwrng device, reading will get stuck if
    the virtio device is reset. We should return error for reading when we
    start to remove the device.
    
    Signed-off-by: Amos Kong <akong@redhat.com>
    Reviewed-by: Amit Shah <amit.shah@redhat.com>
    Cc: stable@vger.kernel.org
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

commit 3856e548372513665670ca5db60d9a74b970fe0d
Author: Amos Kong <akong@redhat.com>
Date:   Thu Sep 11 22:20:39 2014 +0930

    virtio-rng: fix stuck of hot-unplugging busy device
    
    When we try to hot-remove a busy virtio-rng device from QEMU monitor,
    the device can't be hot-removed. Because virtio-rng driver hangs at
    wait_for_completion_killable().
    
    This patch exits the waiting by completing have_data completion before
    unregistering, resets data_avail to avoid the hwrng core use wrong
    buffer bytes.
    
    Signed-off-by: Amos Kong <akong@redhat.com>
    Reviewed-by: Amit Shah <amit.shah@redhat.com>
    Cc: stable@vger.kernel.org
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

commit a937cca270c544c4319572b57b196b2251b07dd2
Author: Jan Kara <jack@suse.cz>
Date:   Wed Sep 10 21:22:51 2014 +0200

    GFS2: Don't use MAXQUOTAS value
    
    MAXQUOTAS value defines maximum number of quota types VFS supports.
    This isn't necessarily the number of types gfs2 supports and with
    addition of project quotas these two numbers stop matching. So make gfs2
    use its private definition.
    
    CC: cluster-devel@redhat.com
    Signed-off-by: Jan Kara <jack@suse.cz>
    Signed-off-by: Steven Whitehouse <swhiteho@redhat.com>

commit 7b7a91152d3c2ddca95172cac1675625cc8dffaf
Author: Benjamin Coddington <bcodding@redhat.com>
Date:   Wed Sep 10 14:09:20 2014 -0400

    GFS2: Hash the negative dentry during inode lookup
    
    Fix a regression introduced by:
    6d4ade986f9c8df31e68 GFS2: Add atomic_open support
    where an early return misses d_splice_alias() which had been
    adding the negative dentry.
    
    Signed-off-by: Benjamin Coddington <bcodding@redhat.com>
    Signed-off-by: Bob Peterson <rpeterso@redhat.com>
    Signed-off-by: Steven Whitehouse <swhiteho@redhat.com>

commit ffff7a12ace24c54220631b79abb02ab65780b5a
Author: Markus Pargmann <mpa@pengutronix.de>
Date:   Mon Sep 8 08:43:37 2014 +0200

    regmap: Fix debugfs-file 'registers' mode
    
    The macro "REGMAP_ALLOW_WRITE_DEBUGFS" can be used to enable write
    support on the registers file in the debugfs. The mode of the file is
    fixed to 0400 so it is not possible to write the file ever.
    
    This patch fixes the mode by setting it to the correct value depending
    on the macro.
    
    Signed-off-by: Markus Pargmann <mpa@pengutronix.de>
    Signed-off-by: Mark Brown <broonie@kernel.org>

commit 78f543a93473f67a1035949a293b79288e259b6e
Author: Stephan Mueller <smueller@chronox.de>
Date:   Mon Sep 1 07:11:20 2014 +0200

    crypto: drbg - remove check for uninitialized DRBG handle
    
    The drbg_healthcheck() contained a test to call the DRBG with an
    uninitialized DRBG cipher handle. As this is an inappropriate use of the
    kernel crypto API to try to generate random numbers before
    initialization, checks verifying for an initialized DRBG have been
    removed in previous patches.
    
    Now, the drbg_healthcheck test must also be removed.
    
    Changes V2: Added patch marker to email subject line.
    
    Signed-off-by: Stephan Mueller <smueller@chronox.de>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit fb38ab4cd05e11184fd2c3ef916fa106ecc505fc
Author: Herbert Xu <herbert@gondor.apana.org.au>
Date:   Fri Sep 5 15:52:28 2014 +0800

    crypto: drbg - backport "fix maximum value checks on 32 bit systems"
    
    This is a backport of commit b9347aff91ce4789619168539f08202d8d6a1177.
    This backport is needed as without it the code will crash on 32-bit
    systems.
    
    The maximum values for additional input string or generated blocks is
    larger than 1<<32. To ensure a sensible value on 32 bit systems, return
    SIZE_MAX on 32 bit systems. This value is lower than the maximum
    allowed values defined in SP800-90A. The standard allow lower maximum
    values, but not larger values.
    
    SIZE_MAX - 1 is used for drbg_max_addtl to allow
    drbg_healthcheck_sanity to check the enforcement of the variable
    without wrapping.
    
    Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
    Reported-by: kbuild test robot <fengguang.wu@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit 2ddfbdd6848d496d8088b28992d257fd02e58c9d
Author: Bob Peterson <rpeterso@redhat.com>
Date:   Wed Aug 20 12:44:45 2014 -0400

    GFS2: Request demote when a "try" flock fails
    
    This patch changes the flock code so that it uses the TRY_1CB flag
    instead of the TRY flag on the first attempt. That forces any holding
    nodes to issue a dlm callback, which requests a demote of the glock.
    Then, if the "try" failed, it sleeps a small amount of time for the
    demote to occur. Then it tries again, for an increasing amount of time.
    Subsequent attempts to gain the "try" lock don't use "_1CB" so that
    only one callback is issued.
    
    Signed-off-by: Bob Peterson <rpeterso@redhat.com>
    Signed-off-by: Steven Whitehouse <swhiteho@redhat.com>

commit b650738cd093a9f9e9551db9ce5cd68acd842dc0
Author: Bob Peterson <rpeterso@redhat.com>
Date:   Wed Aug 6 09:08:36 2014 -0400

    GFS2: Change maxlen variables to size_t
    
    This patch changes some variables (especially maxlen in function
    gfs2_block_map) from unsigned int to size_t. We need 64-bit arithmetic
    for very large files (e.g. 1PB) where the variables otherwise get
    shifted to all 0's.
    
    Signed-off-by: Bob Peterson <rpeterso@redhat.com>
    Signed-off-by: Steven Whitehouse <swhiteho@redhat.com>

commit eaebdedc61ac7bc3dd6ef6eb508097c4aaabef0c
Author: Fabian Frederick <fabf@skynet.be>
Date:   Wed Jul 2 22:08:46 2014 +0200

    GFS2: fs/gfs2/super.c: replace seq_printf by seq_puts
    
    fix checkpatch warnings:
    "WARNING: Prefer seq_puts to seq_printf"
    
    Cc: cluster-devel@redhat.com
    Signed-off-by: Fabian Frederick <fabf@skynet.be>
    Signed-off-by: Steven Whitehouse <swhiteho@redhat.com>