treewide-remove-gfp_temporary-allocation-flag-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#4: 
GFP_TEMPORARY was been introduced by e12ba74d8ff3 ("Group short-lived and

ERROR: "(foo*)" should be "(foo *)"
#588: FILE: fs/proc/base.c:1632:
+	char *tmp = (char*)__get_free_page(GFP_KERNEL);

total: 2 errors, 0 warnings, 451 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/treewide-remove-gfp_temporary-allocation-flag.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Michal Hocko <mhocko@suse.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>