origin
GIT 2d618bdf71635463a4aa4ad0fe46ec852292bc0c

commit 330e261c35dfb969c48f996dbbc8b334b5ee8d9d
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Apr 6 16:28:23 2018 +0200

    hexagon: export csum_partial_copy_nocheck
    
    This is needed to link ipv6 as a loadable module, which in turn happens
    in allmodconfig.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Richard Kuo <rkuo@codeaurora.org>

commit a57ab96ef9dde231d4d46edba4d5f73720edc16a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Apr 6 16:28:22 2018 +0200

    hexagon: add memset_io() helper
    
    We already have memcpy_toio(), but not memset_io(), so let's
    add the obvious version to allow building an allmodconfig kernel
    without errors like
    
    drivers/gpu/drm/ttm/ttm_bo_util.c: In function 'ttm_bo_move_memcpy':
    drivers/gpu/drm/ttm/ttm_bo_util.c:390:3: error: implicit declaration of function 'memset_io' [-Werror=implicit-function-declaration]
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Richard Kuo <rkuo@codeaurora.org>

commit 00ad691ab140b54ab9f5de5e74cb994f552e8124
Author: Arvind Yadav <arvind.yadav.cs@gmail.com>
Date:   Wed Apr 25 20:26:14 2018 +0530

    sparc: vio: use put_device() instead of kfree()
    
    Never directly free @dev after calling device_register(), even
    if it returned an error. Always use put_device() to give up the
    reference initialized.
    
    Signed-off-by: Arvind Yadav <arvind.yadav.cs@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit d3c68d0b4183ddfa05577348a231dd117e6563df
Author: Rob Gardner <rob.gardner@oracle.com>
Date:   Fri Apr 20 12:48:25 2018 -0600

    sparc64: Fix mistake in oradax license text
    
    The license text in both oradax files mistakenly specifies "version 3" of
    the GNU General Public License.  This is corrected to specify "version 2".
    
    Signed-off-by: Rob Gardner <rob.gardner@oracle.com>
    Signed-off-by: Jonathan Helman <jonathan.helman@oracle.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>

commit b4678df184b314a2bd47d2329feca2c2534aa12b
Author: Matthew Wilcox <willy@infradead.org>
Date:   Tue Apr 24 14:02:57 2018 -0700

    errseq: Always report a writeback error once
    
    The errseq_t infrastructure assumes that errors which occurred before
    the file descriptor was opened are of no interest to the application.
    This turns out to be a regression for some applications, notably Postgres.
    
    Before errseq_t, a writeback error would be reported exactly once (as
    long as the inode remained in memory), so Postgres could open a file,
    call fsync() and find out whether there had been a writeback error on
    that file from another process.
    
    This patch changes the errseq infrastructure to report errors to all
    file descriptors which are opened after the error occurred, but before
    it was reported to any file descriptor.  This restores the user-visible
    behaviour.
    
    Cc: stable@vger.kernel.org
    Fixes: 5660e13d2fd6 ("fs: new infrastructure for writeback error handling and reporting")
    Signed-off-by: Matthew Wilcox <mawilcox@microsoft.com>
    Reviewed-by: Jeff Layton <jlayton@kernel.org>
    Signed-off-by: Jeff Layton <jlayton@redhat.com>

commit 7b38460dc8e4eafba06c78f8e37099d3b34d473c
Author: Darrick J. Wong <darrick.wong@oracle.com>
Date:   Tue Apr 17 19:10:15 2018 -0700

    xfs: don't fail when converting shortform attr to long form during ATTR_REPLACE
    
    Kanda Motohiro reported that expanding a tiny xattr into a large xattr
    fails on XFS because we remove the tiny xattr from a shortform fork and
    then try to re-add it after converting the fork to extents format having
    not removed the ATTR_REPLACE flag.  This fails because the attr is no
    longer present, causing a fs shutdown.
    
    This is derived from the patch in his bug report, but we really
    shouldn't ignore a nonzero retval from the remove call.
    
    Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=199119
    Reported-by: kanda.motohiro@gmail.com
    Reviewed-by: Dave Chinner <dchinner@redhat.com>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

commit 7d83fb14258b9961920cd86f0b921caaeb3ebe85
Author: Darrick J. Wong <darrick.wong@oracle.com>
Date:   Mon Apr 16 23:07:45 2018 -0700

    xfs: prevent creating negative-sized file via INSERT_RANGE
    
    
    During the "insert range" fallocate operation, i_size grows by the
    specified 'len' bytes.  XFS verifies that i_size + len < s_maxbytes, as
    it should.  But this comparison is done using the signed 'loff_t', and
    'i_size + len' can wrap around to a negative value, causing the check to
    incorrectly pass, resulting in an inode with "negative" i_size.  This is
    possible on 64-bit platforms, where XFS sets s_maxbytes = LLONG_MAX.
    ext4 and f2fs don't run into this because they set a smaller s_maxbytes.
    
    Fix it by using subtraction instead.
    
    Reproducer:
        xfs_io -f file -c "truncate $(((1<<63)-1))" -c "finsert 0 4096"
    
    Fixes: a904b1ca5751 ("xfs: Add support FALLOC_FL_INSERT_RANGE for fallocate")
    Cc: <stable@vger.kernel.org> # v4.1+
    Originally-From: Eric Biggers <ebiggers@google.com>
    Signed-off-by: Eric Biggers <ebiggers@google.com>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    [darrick: fix signed integer addition overflow too]
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

commit 2c4306f719b083d17df2963bc761777576b8ad1b
Author: Eric Sandeen <sandeen@redhat.com>
Date:   Mon Apr 16 23:07:27 2018 -0700

    xfs: set format back to extents if xfs_bmap_extents_to_btree
    
    If xfs_bmap_extents_to_btree fails in a mode where we call
    xfs_iroot_realloc(-1) to de-allocate the root, set the
    format back to extents.
    
    Otherwise we can assume we can dereference ifp->if_broot
    based on the XFS_DINODE_FMT_BTREE format, and crash.
    
    Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=199423
    Signed-off-by: Eric Sandeen <sandeen@redhat.com>
    Reviewed-by: Christoph Hellwig <hch@lst.de>
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

commit b42db0860e13067fcc7cbfba3966c9e652668bbc
Author: Eric Sandeen <sandeen@sandeen.net>
Date:   Mon Apr 16 23:06:53 2018 -0700

    xfs: enhance dinode verifier
    
    Add several more validations to xfs_dinode_verify:
    
    - For LOCAL data fork formats, di_nextents must be 0.
    - For LOCAL attr fork formats, di_anextents must be 0.
    - For inodes with no attr fork offset,
      - format must be XFS_DINODE_FMT_EXTENTS if set at all
      - di_anextents must be 0.
    
    Thanks to dchinner for pointing out a couple related checks I had
    forgotten to add.
    
    Signed-off-by: Eric Sandeen <sandeen@redhat.com>
    Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=199377
    Reviewed-by: Darrick J. Wong <darrick.wong@oracle.com>
    Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>