pid-remove-pidhash-checkpatch-fixes
ERROR: space required before the open parenthesis '('
#136: FILE: kernel/pid.c:121:
+		switch(--ns->pid_allocated) {

total: 1 errors, 0 warnings, 188 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/pid-remove-pidhash.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Gargi Sharma <gs051095@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>