mm: thp: avoid uninitialized variable use
When the down_read_trylock() fails, 'vma' has not been initialized yet,
which gcc now warns about:

mm/khugepaged.c: In function 'khugepaged':
mm/khugepaged.c:1659:25: error: 'vma' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Presumably we are not supposed to call find_vma() without the mmap_sem
either, so setting it to NULL for this case seems appropriate.

Link: http://lkml.kernel.org/r/20171215125129.2948634-1-arnd@arndb.de
Fixes: 0951b59acf3a ("mm: thp: use down_read_trylock() in khugepaged to avoid long block")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Michal Hocko <mhocko@suse.com>
Cc: "Yang Shi" <yang.s@alibaba-inc.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>