x86_64-add-kasan-support-fix
Combination of CONFIG_SPARSEMEM_VMEMMAP=n, CONFIG_KASAN=y
cause build error:
	arch/x86/built-in.o: In function `populate_zero_shadow':
	kasan_init_64.c:(.init.text+0xe2cc): undefined reference to
	`vmemmap_alloc_block'
	kasan_init_64.c:(.init.text+0xe3ab): undefined reference to
	`vmemmap_alloc_block'
	kasan_init_64.c:(.init.text+0xe483): undefined reference to
	`vmemmap_alloc_block'
	arch/x86/built-in.o: In function `kasan_init':
	(.init.text+0xe65d): undefined reference to `vmemmap_populate'
	arch/x86/built-in.o: In function `kasan_init':
	(.init.text+0xe6ea): undefined reference to `vmemmap_populate'
	make: *** [vmlinux] Error 1

x86_64-specific part of KASAN depends on SPARSEMEM_VMEMMAP.
Express this in Kconfig.

Signed-off-by: Andrey Ryabinin <a.ryabinin@samsung.com>
Reported-by: Jim Davis <jim.epost@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>