origin
GIT ebe6e90ccc6679cb01d2b280e4b61e6092d4bedb

commit 8d30371fd7c328e192d7ea3108bd71b903631d6a
Author: Johannes Thumshirn <jthumshirn@suse.de>
Date:   Tue Oct 10 17:31:38 2017 +0200

    scsi: fc: check for rport presence in fc_block_scsi_eh
    
    Coverity-scan recently found a possible NULL pointer dereference in
    fc_block_scsi_eh() as starget_to_rport() either returns the rport for
    the startget or NULL.
    
    While it is rather unlikely to have fc_block_scsi_eh() called without an
    rport associated it's a good idea to catch potential misuses of the API
    gracefully.
    
    Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
    Reviewed-by: Bart Van Assche <bart.vanassche@wdc.com>
    Reviewed-by: Hannes Reinecke <hare@suse.de>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit a9e170e28636fd577249f39029d59e4e960a42b8
Author: Quinn Tran <quinn.tran@cavium.com>
Date:   Tue Oct 10 12:08:22 2017 -0700

    scsi: qla2xxx: Fix uninitialized work element
    
    Fixes following stack trace
    
    kernel: Call Trace:
    kernel: dump_stack+0x63/0x84
    kernel: __warn+0xd1/0xf0
    kernel: warn_slowpath_null+0x1d/0x20
    kernel: __queue_work+0x37a/0x420
    kernel: queue_work_on+0x27/0x40
    kernel: queue_work+0x14/0x20 [qla2xxx]
    kernel: schedule_work+0x13/0x20 [qla2xxx]
    kernel: qla2x00_post_work+0xab/0xb0 [qla2xxx]
    kernel: qla2x00_post_aen_work+0x3b/0x50 [qla2xxx]
    kernel: qla2x00_async_event+0x20d/0x15d0 [qla2xxx]
    kernel: ? lock_timer_base+0x7d/0xa0
    kernel: qla24xx_intr_handler+0x1da/0x310 [qla2xxx]
    kernel: qla2x00_poll+0x36/0x60 [qla2xxx]
    kernel: qla2x00_mailbox_command+0x659/0xec0 [qla2xxx]
    kernel: ? proc_create_data+0x7a/0xd0
    kernel: qla25xx_init_rsp_que+0x15b/0x240 [qla2xxx]
    kernel: ? request_irq+0x14/0x20 [qla2xxx]
    kernel: qla25xx_create_rsp_que+0x256/0x3c0 [qla2xxx]
    kernel: qla2xxx_create_qpair+0x2af/0x5b0 [qla2xxx]
    kernel: qla2x00_probe_one+0x1107/0x1c30 [qla2xxx]
    
    Fixes: ec7193e26055 ("qla2xxx: Fix delayed response to command for loop mode/direct connect.")
    Cc: <stable@vger.kernel.org> # 4.13
    Signed-off-by: Quinn Tran <quinn.tran@cavium.com>
    Signed-off-by: Himanshu Madhani <himanshu.madhani@cavium.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit eef9ffdf9cd39b2986367bc8395e2772bc1284ba
Author: Johannes Thumshirn <jthumshirn@suse.de>
Date:   Mon Oct 9 13:33:19 2017 +0200

    scsi: libiscsi: fix shifting of DID_REQUEUE host byte
    
    The SCSI host byte should be shifted left by 16 in order to have
    scsi_decide_disposition() do the right thing (.i.e. requeue the
    command).
    
    Signed-off-by: Johannes Thumshirn <jthumshirn@suse.de>
    Fixes: 661134ad3765 ("[SCSI] libiscsi, bnx2i: make bound ep check common")
    Cc: Lee Duncan <lduncan@suse.com>
    Cc: Hannes Reinecke <hare@suse.de>
    Cc: Bart Van Assche <Bart.VanAssche@sandisk.com>
    Cc: Chris Leech <cleech@redhat.com>
    Acked-by: Lee Duncan <lduncan@suse.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit ead666000a5fe34bdc82d61838e4df2d416ea15e
Author: Mauro Carvalho Chehab <mchehab@s-opensource.com>
Date:   Tue Sep 12 05:58:26 2017 -0400

    media: dvb_frontend: only use kref after initialized
    
    As reported by Laurent, when a DVB frontend need to register
    two drivers (e. g. a tuner and a demod), if the second driver
    fails to register (for example because it was not compiled),
    the error handling logic frees the frontend by calling
    dvb_frontend_detach(). That used to work fine, but changeset
    1f862a68df24 ("[media] dvb_frontend: move kref to struct dvb_frontend")
    added a kref at struct dvb_frontend. So, now, instead of just
    freeing the data, the error handling do a kref_put().
    
    That works fine only after dvb_register_frontend() succeeds.
    
    While it would be possible to add a helper function that
    would be initializing earlier the kref, that would require
    changing every single DVB frontend on non-trivial ways, and
    would make frontends different than other drivers.
    
    So, instead of doing that, let's focus on the real issue:
    only call kref_put() after kref_init(). That's easy to
    check, as, when the dvb frontend is successfuly registered,
    it will allocate its own private struct. So, if such
    struct is allocated, it means that it is safe to use
    kref_put(). If not, then nobody is using yet the frontend,
    and it is safe to just deallocate it.
    
    Fixes: 1f862a68df24 ("[media] dvb_frontend: move kref to struct dvb_frontend")
    
    Reported-by: Laurent Pinchart <laurent.pinchart+renesas@ideasonboard.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>

commit d1b3f51ee1eab3a6db1b09a60e61280c48eb0b01
Author: Satish Kharat <satishkh@cisco.com>
Date:   Thu Oct 5 16:41:21 2017 -0700

    scsi: libfc: fix a deadlock in fc_rport_work
    
    In places like fc_rport_recv_plogi_req and fcoe_ctlr_vn_add we always
    take the lport disc_mutex lock before the rports mutex
    (rp_mutex) lock. Gaurding list_del_rcu(&rdata->peers) with
    disc.disc_mutex in fc_rport_work is correct but the rp_mutex lock
    can and should to be dropped before taking that lock else results
    in a deadlock.
    
    Signed-off-by: Satish Kharat <satishkh@cisco.com>
    Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit fbce4d97fd4333bcffd00a73b9d98412be630332
Author: Hannes Reinecke <hare@suse.de>
Date:   Wed Oct 4 10:28:56 2017 +0200

    scsi: fixup kernel warning during rmmod()
    
    Calling rmmod() on a FC driver will results in warnings like
    
    WARNING: CPU: 60 PID: 14640 at fs/sysfs/group.c:237 device_del+0x54/0x240()
    sysfs group ffffffff81eff140 not found for kobject '3:0:0:3'
    
    The problem here is that during scsi_remove_target() we will iterate
    over all devices, but fail to remove any of those as the call to
    scsi_device_get() fails the check to module_is_live().  Hence the
    devices will not be removed at this point, but all intermediate
    structures like fc rport etc. will be.  Later on during
    scsi_forget_host() the devices are removed for real, but the device
    parent is already removed and causes this warning.
    
    Signed-off-by: Hannes Reinecke <hare@suse.com>
    Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
    Reviewed-by: Kyle Fortin <kyle.fortin@oracle.com>
    Tested-by: Don Brace <don.brace@microsemi.com>
    Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

commit db6321a1af8432df983048d2dd8529525589f71d
Author: Geert Uytterhoeven <geert@linux-m68k.org>
Date:   Mon Sep 11 08:35:36 2017 -0400

    media: platform: VIDEO_QCOM_CAMSS should depend on HAS_DMA
    
    If NO_DMA=y:
    
        warning: (TOUCHSCREEN_SUR40 && VIDEO_TW68 && VIDEO_CX23885 && VIDEO_CX25821 && VIDEO_CX88 && VIDEO_SAA7134 && VIDEO_COBALT && VIDEO_QCOM_CAMSS) selects VIDEOBUF2_DMA_SG which has unmet direct dependencies (MEDIA_SUPPORT && HAS_DMA)
    
    and
    
        ERROR: "bad_dma_ops" [drivers/media/v4l2-core/videobuf2-dma-sg.ko] undefined!
        ERROR: "bad_dma_ops" [drivers/media/platform/qcom/camss-8x16/qcom-camss.ko] undefined!
    
    VIDEO_QCOM_CAMSS selects VIDEOBUF2_DMA_SG, which bypasses its dependency
    on HAS_DMA.  Make VIDEO_QCOM_CAMSS depend on HAS_DMA to fix this.
    
    Fixes: f5c074947f56533c ("media: camss: Enable building")
    
    Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>

commit 845d6524d69b40bd6abd61dc1264a8657159aa55
Author: Jose Abreu <Jose.Abreu@synopsys.com>
Date:   Thu Sep 14 11:23:38 2017 -0400

    media: cec: Respond to unregistered initiators, when applicable
    
    Running CEC 1.4 compliance test we get the following error on test
    11.1.6.2: "ERROR: The DUT did not broadcast a
    <Report Physical Address> message to the unregistered device."
    
    Fix this by letting GIVE_PHYSICAL_ADDR message respond to unregistered
    device. Also, GIVE_DEVICE_VENDOR_ID and GIVE_FEATURES fall in the
    same category so, respond also to these messages.
    
    With this fix we pass CEC 1.4 official compliance.
    
    Signed-off-by: Jose Abreu <joabreu@synopsys.com>
    Cc: Joao Pinto <jpinto@synopsys.com>
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Cc: <stable@vger.kernel.org>      # for v4.10 and up
    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>

commit e949f61461ab83b094cad564c89a8d2b078b4508
Author: Hans Verkuil <hverkuil@xs4all.nl>
Date:   Thu Aug 31 12:56:10 2017 -0400

    media: s5p-cec: add NACK detection support
    
    The s5p-cec driver returned CEC_TX_STATUS_ERROR for the NACK condition.
    
    Some digging into the datasheet uncovered the S5P_CEC_TX_STAT1 register where
    bit 0 indicates if the transmit was nacked or not.
    
    Use this to return the correct CEC_TX_STATUS_NACK status to userspace.
    
    This was the only driver that couldn't tell a NACK from another error, and
    that was very unusual. And a potential problem for applications as well.
    
    Tested with my Odroid-U3.
    
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Acked-by: Sylwester Nawrocki <s.nawrocki@samsung.com>
    Cc: <stable@vger.kernel.org>      # for v4.12 and up
    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>

commit 81b79c71e546fc15e95e804de2497a448cc51a47
Author: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Date:   Wed Aug 30 13:14:36 2017 -0400

    media: staging/imx: Fix uninitialized variable warning
    
    The ret variable can be returned uninitialized in the
    imx_media_create_pad_vdev_lists() function is imxmd->num_vdevs is zero.
    Fix it.
    
    Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
    Signed-off-by: Hans Verkuil <hansverk@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>

commit 9b62ccdbc797ae42342bd6ca15719362d2543d24
Author: Colin Ian King <colin.king@canonical.com>
Date:   Tue Aug 29 06:21:10 2017 -0400

    media: qcom: camss: Make function vfe_set_selection static
    
    The function vfe_set_selection is local to the source and does
    not need to be in global scope, so make it static.
    
    Cleans up sparse warning:
    warning: symbol 'vfe_set_selection' was not declared. Should it be static?
    
    Signed-off-by: Colin Ian King <colin.king@canonical.com>
    Acked-by: Todor Tomov <todor.tomov@linaro.org>
    Signed-off-by: Hans Verkuil <hansverk@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>

commit bbd770aee018c8f46d8f43263928440d5ac04b36
Author: Stanimir Varbanov <stanimir.varbanov@linaro.org>
Date:   Tue Aug 29 04:19:43 2017 -0400

    media: venus: init registered list on streamoff
    
    Add missing init_list_head for the registered buffer list.
    Absence of the init could lead to a unhandled kernel paging
    request as below, when streamon/streamoff are called in row.
    
    [338046.571321] Unable to handle kernel paging request at virtual address fffffffffffffe00
    [338046.574849] pgd = ffff800034820000
    [338046.582381] [fffffffffffffe00] *pgd=00000000b60f5003[338046.582545]
    , *pud=00000000b1f31003
    , *pmd=0000000000000000[338046.592082]
    [338046.597754] Internal error: Oops: 96000004 [#1] PREEMPT SMP
    [338046.601671] Modules linked in: venus_enc venus_dec venus_core
    usb_f_ecm g_ether usb_f_rndis u_ether libcomposite ipt_MASQUERADE
    nf_nat_masquerade_ipv4 arc4 wcn36xx mac80211 btqcomsmd btqca iptable_nat
    nf_co]
    [338046.662408] CPU: 0 PID: 5433 Comm: irq/160-venus Tainted: G        W
    4.9.39+ #232
    [338046.668024] Hardware name: Qualcomm Technologies, Inc. APQ 8016 SBC
    (DT)
    [338046.675268] task: ffff80003541cb00 task.stack: ffff800026e20000
    [338046.682097] PC is at venus_helper_release_buf_ref+0x28/0x88
    [venus_core]
    [338046.688282] LR is at vdec_event_notify+0xe8/0x150 [venus_dec]
    [338046.695029] pc : [<ffff000000af6c48>] lr : [<ffff000000a6fc60>]
    pstate: a0000145
    [338046.701256] sp : ffff800026e23bc0
    [338046.708494] x29: ffff800026e23bc0 x28: 0000000000000000
    [338046.718853] x27: ffff000000afd4f8 x26: ffff800031faa700
    [338046.729253] x25: ffff000000afd790 x24: ffff800031faa618
    [338046.739664] x23: ffff800003e18138 x22: ffff800002fc9810
    [338046.750109] x21: ffff800026e23c28 x20: 0000000000000001
    [338046.760592] x19: ffff80002a13b800 x18: 0000000000000010
    [338046.771099] x17: 0000ffffa3d01600 x16: ffff000008100428
    [338046.781654] x15: 0000000000000006 x14: ffff000089045ba7
    [338046.792250] x13: ffff000009045bb6 x12: 00000000004f37c8
    [338046.802894] x11: 0000000000267211 x10: 0000000000000000
    [338046.813574] x9 : 0000000000032000 x8 : 00000000dc400000
    [338046.824274] x7 : 0000000000000000 x6 : ffff800031faa728
    [338046.835005] x5 : ffff80002a13b850 x4 : 0000000000000000
    [338046.845793] x3 : fffffffffffffdf8 x2 : 0000000000000000
    [338046.856602] x1 : 0000000000000003 x0 : ffff80002a13b800
    
    Signed-off-by: Stanimir Varbanov <stanimir.varbanov@linaro.org>
    Signed-off-by: Hans Verkuil <hansverk@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>

commit b4756707152700c96acdfe149cb1ca4cec306c7a
Author: Sean Young <sean@mess.org>
Date:   Sat Sep 2 07:42:42 2017 -0400

    media: dvb: i2c transfers over usb cannot be done from stack
    
    Since commit 29d2fef8be11 ("usb: catch attempts to submit urbs
    with a vmalloc'd transfer buffer"), the AverMedia AverTV DVB-T
    USB 2.0 (a800) fails to probe.
    
    Cc: stable@vger.kernel.org
    Signed-off-by: Sean Young <sean@mess.org>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@s-opensource.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>