ARM: avoid ARCH_MMAP_RND_BITS for NOMMU
ARM kernels with MMU disabled fail to build because of CONFIG_ARCH_MMAP_RND_BITS:

kernel/built-in.o:(.data+0x754): undefined reference to `mmap_rnd_bits'
kernel/built-in.o:(.data+0x76c): undefined reference to `mmap_rnd_bits_min'
kernel/built-in.o:(.data+0x770): undefined reference to `mmap_rnd_bits_max'

This changes the newly added line to only select this allow for
MMU-enabled kernels.

Fixes: 14570b3fd31a ("arm: mm: support ARCH_MMAP_RND_BITS")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Daniel Cashman <dcashman@google.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>