mm: include linux/pfn.h for PHYS_PFN definition
A change to asm-generic/memory_model.h caused a new build error
in some configurations:

mach-clps711x/common.c:39:10: error: implicit declaration of function 'PHYS_PFN'
   .pfn  = __phys_to_pfn(CLPS711X_PHYS_BASE),

This includes the linux/pfn.h header from the same file to avoid the
error.

Fixes: bf1c6c9895de ("mm: add PHYS_PFN, use it in __phys_to_pfn()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Chen Gang <xili_gchen_5257@hotmail.com>
Cc: Chen Gang <gang.chen.5i5j@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>