origin
GIT 7b43b47373d40d557cd7e1a84a0bd8ebc4d745ab

commit b18042a673e88c9457a6d1716219c2367ca447b0
Author: Antti Palosaari <crope@iki.fi>
Date:   Sat Mar 14 13:03:55 2015 -0300

    [media] rtl28xxu: return success for unimplemented FE callback
    
    Return success for FE callback on case we don't have any special
    implementation. fc0013 tuner driver calls that callback in order to
    switch antenna input, even we don't provide antenna switch.
    Returning error caused fc0013 driver given up tuning.
    
    Signed-off-by: Antti Palosaari <crope@iki.fi>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit b3b2bf820e82d7581462dea28a9c3af1bd8cc747
Author: Antti Palosaari <crope@iki.fi>
Date:   Sat Mar 14 11:13:07 2015 -0300

    [media] rtl2832: disable regmap register cache
    
    Caching register reads causes some random I/O errors on channel
    change. Disable caching now in order to avoid those errors.
    
    Reverts partly commit dcadb82
    
    Signed-off-by: Antti Palosaari <crope@iki.fi>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 4879785ed511083676f27a016c9ad6c46c8e5737
Author: Sakari Ailus <sakari.ailus@linux.intel.com>
Date:   Fri Feb 13 04:42:37 2015 -0300

    [media] vb2: Fix dma_dir setting for dma-contig mem type
    
    The last argument of vb2_dc_get_user_pages() is of type enum
    dma_data_direction, but the caller, vb2_dc_get_userptr() passes a value
    which is the result of comparison dma_dir == DMA_FROM_DEVICE. This results
    in the write parameter to get_user_pages() being zero in all cases, i.e.
    that the caller has no intent to write there.
    
    This was broken by patch "vb2: replace 'write' by 'dma_dir'".
    
    Signed-off-by: Sakari Ailus <sakari.ailus@linux.intel.com>
    Cc: stable@vger.kernel.org  # for v3.19
    Acked-by: Hans Verkuil <hans.verkuil@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit a0f10c131cc49d7d84394beb7903e1f246331224
Author: Marek Szyprowski <m.szyprowski@samsung.com>
Date:   Wed Mar 4 05:55:22 2015 -0800

    [media] media: s5p-mfc: fix broken pointer cast on 64bit arch
    
    Unsigned int cannot be used to store casted pointer on 64bit
    architecture, so correct such casts to properly use unsigned long
    variables.
    
    Signed-off-by: Marek Szyprowski <m.szyprowski@samsung.com>
    Signed-off-by: Kamil Debski <k.debski@samsung.com>
    [k.debski@samsung.com: removed volatile and __iomem from cast]
    
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 05b676ab42f624425d5f6519276e506b812fa058
Author: Marek Szyprowski <m.szyprowski@samsung.com>
Date:   Wed Mar 4 05:55:21 2015 -0800

    [media] media: s5p-mfc: fix mmap support for 64bit arch
    
    TASK_SIZE is depends on the systems architecture (32 or 64 bits) and it
    should not be used for defining offset boundary for mmaping buffers for
    CAPTURE and OUTPUT queues. This patch fixes support for MMAP calls on
    the CAPTURE queue on 64bit architectures (like ARM64).
    
    Cc: stable@vger.kernel.org
    Signed-off-by: Marek Szyprowski <m.szyprowski@samsung.com>
    Signed-off-by: Kamil Debski <k.debski@samsung.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 6b46211f0a3b18b2360275ac29c4d6bfdf7bc015
Author: Hans Verkuil <hverkuil@xs4all.nl>
Date:   Sun Mar 8 23:20:03 2015 -0800

    [media] cx23885: fix querycap
    
    cap->device_caps wasn't set in cx23885-417.c causing a warning from
    the v4l2-core.
    
    Reported-by: Joseph Jasi <joe.yasi@gmail.com>
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Cc: <stable@vger.kernel.org>      # for v3.19 and up
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit ab3120300be067a2d41a027c41db0b2c662ab200
Author: Hans Verkuil <hverkuil@xs4all.nl>
Date:   Wed Dec 10 12:35:34 2014 -0300

    [media] sh_veu: v4l2_dev wasn't set
    
    The v4l2_dev field of struct video_device must be set correctly.
    This was never done for this driver, so no video nodes were created
    anymore.
    
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Cc: <stable@vger.kernel.org>      # for v3.11 and up
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 41f03a00536ebb3d72c051f9e7efe2d4ab76ebc8
Author: Kamil Debski <k.debski@samsung.com>
Date:   Tue Mar 3 11:32:58 2015 -0300

    [media] s5p-mfc: Fix NULL pointer dereference caused by not set q->lock
    
    The patch "media: s5p-mfc: use vb2_ops_wait_prepare/finish helper"
    (654a731be1a0b6f606f3f3d12b50db08f2ae3c3) introduced a kernel panic.
    The q->lock was set for just one queue, the other was not set thus causing
    a NULL pointer dereference.
    
    Reported-by: Marek Szyprowski <m.szyprowski@samsung.com>
    Signed-off-by: Kamil Debski <k.debski@samsung.com>
    Signed-off-by: Sylwester Nawrocki <s.nawrocki@samsung.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit f7cbd688f039a3adefc9210226b7edf5bd8fd6cd
Author: Jacek Anaszewski <j.anaszewski@samsung.com>
Date:   Wed Feb 25 08:53:49 2015 -0300

    [media] s5p-jpeg: exynos3250: fix erroneous reset procedure
    
    The first while loop in the function exynos3250_jpeg_reset had no chance
    to be executed because the reg variable was initialized to 0.
    Initialize reg variable to 1 to fix the issue.
    
    Signed-off-by: Jacek Anaszewski <j.anaszewski@samsung.com>
    Reported-by: Andrzej Pietrasiewicz <andrzej.p@samsung.com>
    Signed-off-by: Sylwester Nawrocki <s.nawrocki@samsung.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 3987c98461e3886031a563679cf22e73ba900b5a
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Thu Jan 29 13:13:08 2015 -0300

    [media] s5p-tv: hdmi needs I2C support
    
    Building the s5p-tv HDMI support when CONFIG_I2C is disabled
    gives us this build error:
    
    s5p-tv/hdmi_drv.c: In function 'hdmi_probe':
    s5p-tv/hdmi_drv.c:947:2: error: implicit declaration of function 'i2c_get_adapter' [-Werror=implicit-function-declaration]
      adapter = i2c_get_adapter(pdata->hdmiphy_bus);
      ^
    
    This patch changes the Kconfig description to include I2C
    as a dependency for this driver, so it cannot be configured
    incorrectly.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: Sylwester Nawrocki <s.nawrocki@samsung.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit cb0c3f5f1b888fa0283c2581c91bb10728ac1b22
Author: Tony K Nadackal <tony.kn@samsung.com>
Date:   Wed Dec 17 04:21:21 2014 -0300

    [media] s5p-jpeg: Initialize cb and cr to zero
    
    To avoid garbage value written into image base address planes,
    initialize cb and cr of structure s5p_jpeg_addr to zero.
    
    Signed-off-by: Tony K Nadackal <tony.kn@samsung.com>
    Signed-off-by: Sylwester Nawrocki <s.nawrocki@samsung.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit d5c00762ec5db2f7a7c0b54415b7df364c78d39d
Author: Randy Dunlap <rdunlap@infradead.org>
Date:   Mon Feb 23 15:20:22 2015 -0300

    [media] media: fix gspca drivers build dependencies
    
    Several (15) drivers in media/usb/gspca use IF_ENABLED(CONFIG_INPUT)
    to decide if they should call input* interfaces, but those drivers
    do not build successfully when CONFIG_INPUT=m and the gspca drivers
    are builtin (=y).  Making USB_GSPCA depend on INPUT || INPUT=n
    fixes the build dependencies and allows all of them to build
    cleanly.
    
    Fixes these build errors (selections, not all are listed):
    
    drivers/built-in.o: In function `gspca_disconnect':
    (.text+0x32ed0f): undefined reference to `input_unregister_device'
    drivers/built-in.o: In function `sd_isoc_irq':
    konica.c:(.text+0x333098): undefined reference to `input_event'
    konica.c:(.text+0x3330ab): undefined reference to `input_event'
    drivers/built-in.o: In function `sd_stopN':
    konica.c:(.text+0x3338d3): undefined reference to `input_event'
    konica.c:(.text+0x3338e5): undefined reference to `input_event'
    drivers/built-in.o: In function `ov51x_handle_button':
    ov519.c:(.text+0x335ddb): undefined reference to `input_event'
    drivers/built-in.o:ov519.c:(.text+0x335ded): more undefined references to `input_event' follow
    pac7302.c:(.text+0x336ea1): undefined reference to `input_event'
    pac7302.c:(.text+0x336eb3): undefined reference to `input_event'
    drivers/built-in.o: In function `sd_pkt_scan':
    spca561.c:(.text+0x338fd8): undefined reference to `input_event'
    drivers/built-in.o:spca561.c:(.text+0x338feb): more undefined references to `input_event' follow
    t613.c:(.text+0x33a6fd): undefined reference to `input_event'
    drivers/built-in.o:t613.c:(.text+0x33a70f): more undefined references to `input_event' follow
    
    Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
    Cc:	Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Hans de Goede <hdegoede@redhat.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 8e48a2d54c5d74ea3e9dc4c3b9037786bb447f36
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Thu Feb 19 06:47:16 2015 -0300

    [media] soc-camera: Fix devm_kfree() in soc_of_bind()
    
    Unlike scan_async_group(), soc_of_bind() doesn't allocate its
    soc_camera_async_client structure using devm_kzalloc(), but has it
    embedded inside the soc_of_info structure.  Hence on failure, it must
    free the whole soc_of_info structure, and not just the embedded
    soc_camera_async_client structure, as the latter causes a warning, and
    may cause slab corruption:
    
        soc-camera-pdrv soc-camera-pdrv.0: Probing soc-camera-pdrv.0
        ------------[ cut here ]------------
        WARNING: CPU: 0 PID: 1 at drivers/base/devres.c:887 devm_kfree+0x30/0x40()
        CPU: 0 PID: 1 Comm: swapper/0 Not tainted 3.19.0-shmobile-08386-g37feb0d093cb2d8e #128
        Hardware name: Generic R8A7791 (Flattened Device Tree)
        Backtrace:
        [<c0011e7c>] (dump_backtrace) from [<c0012024>] (show_stack+0x18/0x1c)
         r6:c05a923b r5:00000009 r4:00000000 r3:00204140
        [<c001200c>] (show_stack) from [<c048ed30>] (dump_stack+0x78/0x94)
        [<c048ecb8>] (dump_stack) from [<c002687c>] (warn_slowpath_common+0x8c/0xb8)
         r4:00000000 r3:00000000
        [<c00267f0>] (warn_slowpath_common) from [<c0026980>] (warn_slowpath_null+0x24/0x2c)
         r8:ee7d8214 r7:ed83b810 r6:ed83bc20 r5:fffffffa r4:ed83e510
        [<c002695c>] (warn_slowpath_null) from [<c025e0cc>] (devm_kfree+0x30/0x40)
        [<c025e09c>] (devm_kfree) from [<c032bbf4>] (soc_of_bind.isra.14+0x194/0x1d4)
        [<c032ba60>] (soc_of_bind.isra.14) from [<c032c6b8>] (soc_camera_host_register+0x208/0x31c)
         r9:00000070 r8:ee7e05d0 r7:ee153210 r6:00000000 r5:ee7e0218 r4:ed83bc20
        [<c032c4b0>] (soc_camera_host_register) from [<c032e80c>] (rcar_vin_probe+0x1f4/0x238)
         r8:ee153200 r7:00000008 r6:ee153210 r5:ed83bc10 r4:c066319c r3:000000c0
        [<c032e618>] (rcar_vin_probe) from [<c025c334>] (platform_drv_probe+0x50/0xa0)
         r10:00000000 r9:c0662fa8 r8:00000000 r7:c06a3700 r6:c0662fa8 r5:ee153210
         r4:00000000
        [<c025c2e4>] (platform_drv_probe) from [<c025af08>] (driver_probe_device+0xc4/0x208)
         r6:c06a36f4 r5:00000000 r4:ee153210 r3:c025c2e4
        [<c025ae44>] (driver_probe_device) from [<c025b108>] (__driver_attach+0x70/0x94)
         r9:c066f9c0 r8:c0624a98 r7:c065b790 r6:c0662fa8 r5:ee153244 r4:ee153210
        [<c025b098>] (__driver_attach) from [<c025984c>] (bus_for_each_dev+0x74/0x98)
         r6:c025b098 r5:c0662fa8 r4:00000000 r3:00000001
        [<c02597d8>] (bus_for_each_dev) from [<c025b1dc>] (driver_attach+0x20/0x28)
         r6:ed83c200 r5:00000000 r4:c0662fa8
        [<c025b1bc>] (driver_attach) from [<c025a00c>] (bus_add_driver+0xdc/0x1c4)
        [<c0259f30>] (bus_add_driver) from [<c025b8f4>] (driver_register+0xa4/0xe8)
         r7:c0624a98 r6:00000000 r5:c060b010 r4:c0662fa8
        [<c025b850>] (driver_register) from [<c025ccd0>] (__platform_driver_register+0x50/0x64)
         r5:c060b010 r4:ed8394c0
        [<c025cc80>] (__platform_driver_register) from [<c060b028>] (rcar_vin_driver_init+0x18/0x20)
        [<c060b010>] (rcar_vin_driver_init) from [<c05edde8>] (do_one_initcall+0x108/0x1b8)
        [<c05edce0>] (do_one_initcall) from [<c05edfb4>] (kernel_init_freeable+0x11c/0x1e4)
         r9:c066f9c0 r8:c066f9c0 r7:c062eab0 r6:c06252c4 r5:000000ad r4:00000006
        [<c05ede98>] (kernel_init_freeable) from [<c048c3d0>] (kernel_init+0x10/0xec)
         r9:00000000 r8:00000000 r7:00000000 r6:00000000 r5:c048c3c0 r4:00000000
        [<c048c3c0>] (kernel_init) from [<c000eba0>] (ret_from_fork+0x14/0x34)
         r4:00000000 r3:ee04e000
        ---[ end trace e3a984cc0335c8a0 ]---
        rcar_vin e6ef1000.video: group probe failed: -6
    
    Fixes: 1ddc6a6caa94e1e1 ("[media] soc_camera: add support for dt binding soc_camera drivers")
    
    Cc: <stable@vger.kernel.org> # 3.17+
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Signed-off-by: Guennadi Liakhovetski <g.liakhovetski@gmx.de>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit ce037f19aaef992c634af653b17e61eee30a9404
Author: Josh Wu <josh.wu@atmel.com>
Date:   Tue Nov 25 06:30:25 2014 -0300

    [media] media: atmel-isi: increase the burst length to improve the performance
    
    The burst length could be BEATS_4/8/16. Before this patch, isi use default
    value BEATS_4. To imporve the performance we could set it to BEATS_16.
    
    Otherwise sometime it would cause the ISI overflow error.
    
    Reported-by: Bo Shen <voice.shen@atmel.com>
    Signed-off-by: Josh Wu <josh.wu@atmel.com>
    Signed-off-by: Guennadi Liakhovetski <g.liakhovetski@gmx.de>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 0e661006370b7e7fb9ac9d94f9c3500a62cd559b
Author: Hans Verkuil <hverkuil@xs4all.nl>
Date:   Mon Feb 16 07:49:07 2015 -0300

    [media] vb2: fix 'UNBALANCED' warnings when calling vb2_thread_stop()
    
    Stopping the vb2 thread (as used by several DVB devices) can result
    in an 'UNBALANCED' warning such as this:
    
    vb2: counters for queue ffff880407ee9828: UNBALANCED!
    vb2:     setup: 1 start_streaming: 1 stop_streaming: 1
    vb2:     wait_prepare: 249333 wait_finish: 249334
    
    This is due to a race condition between stopping the thread and
    calling vb2_internal_streamoff(). While I have not been able to deduce
    the exact mechanism how this race condition can produce this warning,
    I can see that the way the stream is stopped is likely to lead to a
    race somewhere.
    
    This patch simplifies how this is done by first ensuring that the
    thread is completely stopped before cleaning up the vb2 queue. It
    does that by setting threadio->stop to true, followed by a call to
    vb2_queue_error() which will wake up the thread. The thread sees that
    'stop' is true and it will exit.
    
    The call to kthread_stop() waits until the thread has exited, and only
    then is the queue cleaned up by calling __vb2_cleanup_fileio().
    
    This is a much cleaner sequence and the warning has now disappeared.
    
    Reported-by: Jurgen Kramer <gtmkramer@xs4all.nl>
    Tested-by: Jurgen Kramer <gtmkramer@xs4all.nl>
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Cc: <stable@vger.kernel.org>      # for v3.18 and up
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>