kmod: add dependencies for test module
When we try to 'select' drivers whose dependencies are not met, we get a
kconfig warning and undefined behavior as further 'select' statements in
those drivers can not be honored:

warning: (TEST_KMOD) selects TUN which has unmet direct dependencies (NETDEVICES && NET_CORE && INET)
warning: (TEST_KMOD) selects XFS_FS which has unmet direct dependencies (BLOCK && (64BIT || LBDAF))
ERROR: "iomap_zero_range" [fs/xfs/xfs.ko] undefined!
ERROR: "iomap_fiemap" [fs/xfs/xfs.ko] undefined!
ERROR: "iomap_page_mkwrite" [fs/xfs/xfs.ko] undefined!

To work around that, this adds the dependencies required by the 'tun',
'xfs' and 'btrfs' modules for CONFIG_TEST_KMOD, guaranteeing that we can
always enable those, and fixing the 'randconfig' issues.

Unfortunately, there is another problem that I have not found a good
solution for: If any of the three drivers are built-in rather than
loadable modules, then the module load test will later fail at runtime.

Fixes: ec159fed8677 ("kmod: add test driver to stress test the module loader")
Link: http://lkml.kernel.org/r/20170630154834.3689272-1-arnd@arndb.de
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: "Luis R. Rodriguez" <mcgrof@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>