mm-respect-foll_force-foll_cow-for-thp-checkpatch-fixes
WARNING: please, no spaces at the start of a line
#101: FILE: mm/huge_memory.c:1143:
+       return pmd_write(pmd) ||$

ERROR: code indent should use tabs where possible
#102: FILE: mm/huge_memory.c:1144:
+               ((flags & FOLL_FORCE) && (flags & FOLL_COW) && pmd_dirty(pmd));$

WARNING: please, no spaces at the start of a line
#102: FILE: mm/huge_memory.c:1144:
+               ((flags & FOLL_FORCE) && (flags & FOLL_COW) && pmd_dirty(pmd));$

total: 1 errors, 2 warnings, 36 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-respect-foll_force-foll_cow-for-thp.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Keno Fischer <keno@juliacomputing.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>