origin
GIT 87ef12027b9b1dd0e0b12cf311fbcb19f9d92539

commit e6f39e87b6439939a14cb7fdd94086a082b63b87
Author: Joerg Roedel <jroedel@suse.de>
Date:   Mon Apr 16 11:43:57 2018 +0200

    x86/ldt: Fix support_pte_mask filtering in map_ldt_struct()
    
    The |= operator will let us end up with an invalid PTE. Use
    the correct &= instead.
    
    [ The bug was also independently reported by Shuah Khan ]
    
    Fixes: fb43d6cb91ef ('x86/mm: Do not auto-massage page protections')
    Acked-by: Andy Lutomirski <luto@kernel.org>
    Acked-by: Dave Hansen <dave.hansen@linux.intel.com>
    Signed-off-by: Joerg Roedel <jroedel@suse.de>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

commit d5edb7f8e7ab9fd5fd54a77d957b1733f117a813
Author: Paolo Bonzini <pbonzini@redhat.com>
Date:   Tue Mar 27 22:46:11 2018 +0200

    kvm: selftests: add vmx_tsc_adjust_test
    
    The test checks the behavior of setting MSR_IA32_TSC in a nested guest,
    and the TSC_OFFSET VMCS field in general.  It also introduces the testing
    infrastructure for Intel nested virtualization.
    
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit dd259935e4eec844dc3e5b8a7cd951cd658b4fb6
Author: Paolo Bonzini <pbonzini@redhat.com>
Date:   Fri Apr 13 11:38:35 2018 +0200

    kvm: x86: move MSR_IA32_TSC handling to x86.c
    
    This is not specific to Intel/AMD anymore.  The TSC offset is available
    in vcpu->arch.tsc_offset.
    
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit e79f245ddec17bbd89d73cd0169dba4be46c9b55
Author: KarimAllah Ahmed <karahmed@amazon.de>
Date:   Sat Apr 14 05:10:52 2018 +0200

    X86/KVM: Properly update 'tsc_offset' to represent the running guest
    
    Update 'tsc_offset' on vmentry/vmexit of L2 guests to ensure that it always
    captures the TSC_OFFSET of the running guest whether it is the L1 or L2
    guest.
    
    Cc: Paolo Bonzini <pbonzini@redhat.com>
    Cc: Radim Krčmář <rkrcmar@redhat.com>
    Cc: kvm@vger.kernel.org
    Cc: linux-kernel@vger.kernel.org
    Reviewed-by: Jim Mattson <jmattson@google.com>
    Suggested-by: Paolo Bonzini <pbonzini@redhat.com>
    Signed-off-by: KarimAllah Ahmed <karahmed@amazon.de>
    [AMD changes, fix update_ia32_tsc_adjust_msr. - Paolo]
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit d93605407af34eb0b7eb8aff6b1eae2cde3cdd22
Author: Ilya Dryomov <idryomov@gmail.com>
Date:   Fri Mar 23 06:14:47 2018 +0100

    rbd: notrim map option
    
    Add an option to turn off discard and write zeroes offload support to
    avoid deprovisioning a fully provisioned image.  When enabled, discard
    requests will fail with -EOPNOTSUPP, write zeroes requests will fall
    back to manually zeroing.
    
    Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
    Tested-by: Hitoshi Kamei <hitoshi.kamei.xm@hitachi.com>

commit 420efbdf4d2358dc12913298ad44d041c6ac0ed6
Author: Ilya Dryomov <idryomov@gmail.com>
Date:   Mon Apr 16 09:32:18 2018 +0200

    rbd: adjust queue limits for "fancy" striping
    
    In order to take full advantage of merging in ceph_file_to_extents(),
    allow object set sized I/Os.  If the layout is not "fancy", an object
    set consists of just one object.
    
    Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

commit c6244b3b23771b258656445dcd212be759265b84
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Wed Apr 4 14:53:39 2018 +0200

    rbd: avoid Wreturn-type warnings
    
    In some configurations gcc cannot see that rbd_assert(0) leads to an
    unreachable code path:
    
      drivers/block/rbd.c: In function 'rbd_img_is_write':
      drivers/block/rbd.c:1397:1: error: control reaches end of non-void function [-Werror=return-type]
      drivers/block/rbd.c: In function '__rbd_obj_handle_request':
      drivers/block/rbd.c:2499:1: error: control reaches end of non-void function [-Werror=return-type]
      drivers/block/rbd.c: In function 'rbd_obj_handle_write':
      drivers/block/rbd.c:2471:1: error: control reaches end of non-void function [-Werror=return-type]
    
    As the rbd_assert() here shows has no extra information beyond the verbose
    BUG(), we can simply use BUG() directly in its place.  This is reliably
    detected as not returning on any architecture, since it doesn't depend
    on the unlikely() comparison that confused gcc.
    
    Fixes: 3da691bf4366 ("rbd: new request handling code")
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Ilya Dryomov <idryomov@gmail.com>
    Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

commit ffdeec7aa41aa61ca4ee68fddf4669df9ce661d1
Author: Yan, Zheng <zyan@redhat.com>
Date:   Mon Mar 26 16:46:39 2018 +0800

    ceph: always update atime/mtime/ctime for new inode
    
    For new inode, atime/mtime/ctime are uninitialized.  Don't compare
    against them.
    
    Cc: stable@kernel.org
    Signed-off-by: "Yan, Zheng" <zyan@redhat.com>
    Reviewed-by: Ilya Dryomov <idryomov@gmail.com>
    Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

commit 34f55d0b3a0a39c95134c0c89173893b846d4c80
Author: Dongsheng Yang <dongsheng.yang@easystack.cn>
Date:   Mon Mar 26 10:22:55 2018 -0400

    rbd: support timeout in rbd_wait_state_locked()
    
    currently, the rbd_wait_state_locked() will wait forever if we
    can't get our state locked. Example:
    
    rbd map --exclusive test1  --> /dev/rbd0
    rbd map test1  --> /dev/rbd1
    dd if=/dev/zero of=/dev/rbd1 bs=1M count=1 --> IO blocked
    
    To avoid this problem, this patch introduce a timeout design
    in rbd_wait_state_locked(). Then rbd_wait_state_locked() will
    return error when we reach a timeout.
    
    This patch allow user to set the lock_timeout in rbd mapping.
    
    Signed-off-by: Dongsheng Yang <dongsheng.yang@easystack.cn>
    Reviewed-by: Ilya Dryomov <idryomov@gmail.com>
    Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

commit 2f18d46683cb3047c41229d57cf7c6e2ee48676f
Author: Ilya Dryomov <idryomov@gmail.com>
Date:   Wed Apr 4 10:15:38 2018 +0200

    rbd: refactor rbd_wait_state_locked()
    
    In preparation for lock_timeout option, make rbd_wait_state_locked()
    return error codes.
    
    Signed-off-by: Ilya Dryomov <idryomov@gmail.com>

commit c7cd882469fc5042a5c84122b4062d7f53076db7
Author: Helge Deller <deller@gmx.de>
Date:   Fri Apr 13 21:54:37 2018 +0200

    parisc: Fix missing binfmt_elf32.o build error
    
    Commit 71d577db01a5 ("parisc: Switch to generic COMPAT_BINFMT_ELF")
    removed the binfmt_elf32.c source file, but missed to drop the object
    file from the list of object files the Makefile, which then results in a
    build error.
    
    Fixes: 71d577db01a5 ("parisc: Switch to generic COMPAT_BINFMT_ELF")
    Reported-by: Guenter Roeck <linux@roeck-us.net>
    Tested-by: Guenter Roeck <linux@roeck-us.net>
    Signed-off-by: Helge Deller <deller@gmx.de>

commit 4e1acd7b31a03f24cc6108d37d005e6b1d48c5d3
Author: Peng Hao <peng.hao2@zte.com.cn>
Date:   Fri Apr 13 08:36:30 2018 +0800

    kvm: selftests: add -std=gnu99 cflags
    
    lib/kvm_util.c: In function ‘kvm_memcmp_hva_gva’:
    lib/kvm_util.c:332:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
    
    So add -std=gnu99 to CFLAGS
    
    Signed-off-by: Peng Hao <peng.hao2@zte.com.cn>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit f0f4cf5b306620282db0c59ff963012e1973e025
Author: Krish Sadhukhan <krish.sadhukhan@oracle.com>
Date:   Wed Apr 11 01:10:16 2018 -0400

    x86: Add check for APIC access address for vmentry of L2 guests
    
    According to the sub-section titled 'VM-Execution Control Fields' in the
    section titled 'Basic VM-Entry Checks' in Intel SDM vol. 3C, the following
    vmentry check must be enforced:
    
        If the 'virtualize APIC-accesses' VM-execution control is 1, the
        APIC-access address must satisfy the following checks:
    
            - Bits 11:0 of the address must be 0.
            - The address should not set any bits beyond the processor's
              physical-address width.
    
    This patch adds the necessary check to conform to this rule. If the check
    fails, we cause the L2 VMENTRY to fail which is what the associated unit
    test (following patch) expects.
    
    Reviewed-by: Mihai Carabas <mihai.carabas@oracle.com>
    Reviewed-by: Konrad Rzeszutek Wilk <konrad.wilk@oracle.com>
    Reviewed-by: Jim Mattson <jmattson@google.com>
    Reviewed-by: Wanpeng Li <wanpengli@tencent.com>
    Signed-off-by: Krish Sadhukhan <krish.sadhukhan@oracle.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit 2698d82e519413c6ad287e6f14b29e0373ed37f8
Author: hu huajun <huhuajun@linux.alibaba.com>
Date:   Wed Apr 11 15:16:40 2018 +0800

    KVM: X86: fix incorrect reference of trace_kvm_pi_irte_update
    
    In arch/x86/kvm/trace.h, this function is declared as host_irq the
    first input, and vcpu_id the second, instead of otherwise.
    
    Signed-off-by: hu huajun <huhuajun@linux.alibaba.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit 8e9b29b61851ba452e33373743fadb52778e9075
Author: KarimAllah Ahmed <karahmed@amazon.de>
Date:   Wed Apr 11 11:16:03 2018 +0200

    X86/KVM: Do not allow DISABLE_EXITS_MWAIT when LAPIC ARAT is not available
    
    If the processor does not have an "Always Running APIC Timer" (aka ARAT),
    we should not give guests direct access to MWAIT. The LAPIC timer would
    stop ticking in deep C-states, so any host deadlines would not wakeup the
    host kernel.
    
    The host kernel intel_idle driver handles this by switching to broadcast
    mode when ARAT is not available and MWAIT is issued with a deep C-state
    that would stop the LAPIC timer. When MWAIT is passed through, we can not
    tell when MWAIT is issued.
    
    So just disable this capability when LAPIC ARAT is not available. I am not
    even sure if there are any CPUs with VMX support but no LAPIC ARAT or not.
    
    Cc: Paolo Bonzini <pbonzini@redhat.com>
    Cc: Radim Krčmář <rkrcmar@redhat.com>
    Reported-by: Wanpeng Li <kernellwp@gmail.com>
    Signed-off-by: KarimAllah Ahmed <karahmed@amazon.de>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit 4d5f26ee310237552a36aa14ceee96d6659153cd
Author: Colin Ian King <colin.king@canonical.com>
Date:   Tue Apr 10 13:38:56 2018 +0100

    kvm: selftests: fix spelling mistake: "divisable" and "divisible"
    
    Trivial fix to spelling mistakes in comment and message text
    
    Signed-off-by: Colin Ian King <colin.king@canonical.com>
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit 386c6ddbda180676b7d9fc375d54a7bdd353d39e
Author: KarimAllah Ahmed <karahmed@amazon.de>
Date:   Tue Apr 10 14:15:46 2018 +0200

    X86/VMX: Disable VMX preemption timer if MWAIT is not intercepted
    
    The VMX-preemption timer is used by KVM as a way to set deadlines for the
    guest (i.e. timer emulation). That was safe till very recently when
    capability KVM_X86_DISABLE_EXITS_MWAIT to disable intercepting MWAIT was
    introduced. According to Intel SDM 25.5.1:
    
    """
    The VMX-preemption timer operates in the C-states C0, C1, and C2; it also
    operates in the shutdown and wait-for-SIPI states. If the timer counts down
    to zero in any state other than the wait-for SIPI state, the logical
    processor transitions to the C0 C-state and causes a VM exit; the timer
    does not cause a VM exit if it counts down to zero in the wait-for-SIPI
    state. The timer is not decremented in C-states deeper than C2.
    """
    
    Now once the guest issues the MWAIT with a c-state deeper than
    C2 the preemption timer will never wake it up again since it stopped
    ticking! Usually this is compensated by other activities in the system that
    would wake the core from the deep C-state (and cause a VMExit). For
    example, if the host itself is ticking or it received interrupts, etc!
    
    So disable the VMX-preemption timer if MWAIT is exposed to the guest!
    
    Cc: Paolo Bonzini <pbonzini@redhat.com>
    Cc: Radim Krčmář <rkrcmar@redhat.com>
    Cc: kvm@vger.kernel.org
    Signed-off-by: KarimAllah Ahmed <karahmed@amazon.de>
    Fixes: 4d5422cea3b61f158d58924cbb43feada456ba5c
    Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

commit 0136c741ff40e03323419feec05fcd594f36a463
Author: Anson Huang <Anson.Huang@nxp.com>
Date:   Wed Mar 28 11:22:38 2018 +0800

    clocksource/drivers/imx-tpm: Add different counter width support
    
    Different TPM modules have different width counters which is 16-bit or 32-bit,
    the counter width can be read from TPM_PARAM register bit[23:16], this patch
    adds dynamic check for counter width to support both 16-bit and 32-bit TPM
    modules.
    
    Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

commit 506a7be93ff773d5d4cf75a59f342865605b4910
Author: Anson Huang <Anson.Huang@nxp.com>
Date:   Wed Mar 28 11:22:37 2018 +0800

    clocksource/drivers/imx-tpm: Correct some registers operation flow
    
    According to i.MX7ULP reference manual, TPM_SC_CPWMS can ONLY be written when
    counter is disabled, TPM_SC_TOF is write-1-clear, TPM_C0SC_CHF is also
    write-1-clear, correct these registers initialization flow;
    
    Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

commit 16328e7bd428937f557a984d8b3378387c17a930
Author: Anson Huang <Anson.Huang@nxp.com>
Date:   Wed Mar 28 11:22:36 2018 +0800

    clocksource/drivers/imx-tpm: Fix typo of clock name
    
    The clock name should be ipg instead of igp.
    
    Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

commit cc01456a0d9a3cbfec85cf23f2ce53323e8fc973
Author: Anson Huang <Anson.Huang@nxp.com>
Date:   Wed Mar 28 11:22:35 2018 +0800

    dt-bindings: timer: tpm: fix typo of clock name
    
    The clock name should be ipg instead of igp.
    
    Signed-off-by: Anson Huang <Anson.Huang@nxp.com>
    Reviewed-by: Rob Herring <robh@kernel.org>
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

commit 1c00289ecd12471ba9733e61aaf1d39883a77b16
Author: Tomer Maimon <tmaimon77@gmail.com>
Date:   Thu Mar 8 17:24:58 2018 +0200

    clocksource/drivers/npcm: Add NPCM7xx timer driver
    
    Add Nuvoton BMC NPCM7xx timer driver.
    
    The clocksource Enable 24-bit TIMER0 and TIMER1 counters,
    while TIMER0 serve as clockevent and TIMER1 serve as clocksource.
    
    Signed-off-by: Tomer Maimon <tmaimon77@gmail.com>
    Reviewed-by: Brendan Higgins <brendanhiggins@xxxxxxxxxx>
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>

commit ff2969c479d97c6221a9835ee0ab4c44513badc6
Author: Tomer Maimon <tmaimon77@gmail.com>
Date:   Thu Mar 8 17:24:57 2018 +0200

    dt-binding: timer: document NPCM7xx timer DT bindings
    
    Added device tree binding documentation for Nuvoton NPCM7xx timer.
    
    Signed-off-by: Tomer Maimon <tmaimon77@gmail.com>
    Acked-by: Rob Herring <robh@kernel.org>
    Reviewed-by: Brendan Higgins <brendanhiggins@google.com>
    Signed-off-by: Daniel Lezcano <daniel.lezcano@linaro.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>