origin
GIT d9cee5d4f66ef36f69b0108dedbad7f7009bb6a8

commit f440c4ee3e53f767974fe60bcbc0b6687a5fb53f
Author: Álvaro Fernández Rojas <noltari@gmail.com>
Date:   Sat May 2 12:08:42 2015 +0200

    hwrng: bcm63xx - Fix driver compilation
    
    - s/clk_didsable_unprepare/clk_disable_unprepare
    - s/prov/priv
    - s/error/ret (bcm63xx_rng_probe)
    
    Fixes: 6229c16060fe ("hwrng: bcm63xx - make use of devm_hwrng_register")
    Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
    Acked-by: Florian Fainelli <f.fainelli@gmail.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit 7829fb09a2b4268b30dd9bc782fa5ebee278b137
Author: Daniel Borkmann <daniel@iogearbox.net>
Date:   Thu Apr 30 04:13:52 2015 +0200

    lib: make memzero_explicit more robust against dead store elimination
    
    In commit 0b053c951829 ("lib: memzero_explicit: use barrier instead
    of OPTIMIZER_HIDE_VAR"), we made memzero_explicit() more robust in
    case LTO would decide to inline memzero_explicit() and eventually
    find out it could be elimiated as dead store.
    
    While using barrier() works well for the case of gcc, recent efforts
    from LLVMLinux people suggest to use llvm as an alternative to gcc,
    and there, Stephan found in a simple stand-alone user space example
    that llvm could nevertheless optimize and thus elimitate the memset().
    A similar issue has been observed in the referenced llvm bug report,
    which is regarded as not-a-bug.
    
    Based on some experiments, icc is a bit special on its own, while it
    doesn't seem to eliminate the memset(), it could do so with an own
    implementation, and then result in similar findings as with llvm.
    
    The fix in this patch now works for all three compilers (also tested
    with more aggressive optimization levels). Arguably, in the current
    kernel tree it's more of a theoretical issue, but imho, it's better
    to be pedantic about it.
    
    It's clearly visible with gcc/llvm though, with the below code: if we
    would have used barrier() only here, llvm would have omitted clearing,
    not so with barrier_data() variant:
    
      static inline void memzero_explicit(void *s, size_t count)
      {
        memset(s, 0, count);
        barrier_data(s);
      }
    
      int main(void)
      {
        char buff[20];
        memzero_explicit(buff, sizeof(buff));
        return 0;
      }
    
      $ gcc -O2 test.c
      $ gdb a.out
      (gdb) disassemble main
      Dump of assembler code for function main:
       0x0000000000400400  <+0>: lea   -0x28(%rsp),%rax
       0x0000000000400405  <+5>: movq  $0x0,-0x28(%rsp)
       0x000000000040040e <+14>: movq  $0x0,-0x20(%rsp)
       0x0000000000400417 <+23>: movl  $0x0,-0x18(%rsp)
       0x000000000040041f <+31>: xor   %eax,%eax
       0x0000000000400421 <+33>: retq
      End of assembler dump.
    
      $ clang -O2 test.c
      $ gdb a.out
      (gdb) disassemble main
      Dump of assembler code for function main:
       0x00000000004004f0  <+0>: xorps  %xmm0,%xmm0
       0x00000000004004f3  <+3>: movaps %xmm0,-0x18(%rsp)
       0x00000000004004f8  <+8>: movl   $0x0,-0x8(%rsp)
       0x0000000000400500 <+16>: lea    -0x18(%rsp),%rax
       0x0000000000400505 <+21>: xor    %eax,%eax
       0x0000000000400507 <+23>: retq
      End of assembler dump.
    
    As gcc, clang, but also icc defines __GNUC__, it's sufficient to define
    this in compiler-gcc.h only to be picked up. For a fallback or otherwise
    unsupported compiler, we define it as a barrier. Similarly, for ecc which
    does not support gcc inline asm.
    
    Reference: https://llvm.org/bugs/show_bug.cgi?id=15495
    Reported-by: Stephan Mueller <smueller@chronox.de>
    Tested-by: Stephan Mueller <smueller@chronox.de>
    Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
    Cc: Theodore Ts'o <tytso@mit.edu>
    Cc: Stephan Mueller <smueller@chronox.de>
    Cc: Hannes Frederic Sowa <hannes@stressinduktion.org>
    Cc: mancha security <mancha1@zoho.com>
    Cc: Mark Charlebois <charlebm@gmail.com>
    Cc: Behan Webster <behanw@converseincode.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

commit fefad2d54beb8aad6bf4ac6daeb74f86f52565de
Author: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Date:   Sun Apr 12 09:09:05 2015 -0300

    [media] v4l: omap4iss: Replace outdated OMAP4 control pad API with syscon
    
    The omap4_ctrl_pad_readl and omap4_ctrl_pad_writel functions have been
    removed by commit efde234674d9 but are still used by the OMAP4 ISS
    driver, resulting in a compilation breakage:
    
    drivers/staging/media/omap4iss/iss_csiphy.c: In function 'omap4iss_csiphy_config':
    drivers/staging/media/omap4iss/iss_csiphy.c:167:2: error: implicit declaration of function 'omap4_ctrl_pad_writel' [-Werror=implicit-function-declaration]
      omap4_ctrl_pad_writel(cam_rx_ctrl,
    
    Fix the problem by using the syscon API to reaplace the control pad API.
    Lookup the syscon instance by compatible name for now as the OMAP4 ISS
    driver doesn't support DT yet.
    
    Fixes: efde234674d9 ("ARM: OMAP4+: control: remove support for legacy pad read/write")
    
    Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
    Acked-by: Sakari Alius <sakari.ailus@iki.fi>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 5a9b06a27db6b006605421658418fb8943a6e217
Author: Koji Matsuoka <koji.matsuoka.xm@renesas.com>
Date:   Sun Mar 29 10:04:56 2015 -0300

    [media] media: soc_camera: rcar_vin: Fix wait_for_completion
    
    When stopping abnormally, a driver can't return from wait_for_completion.
    This patch resolved this problem by changing wait_for_completion_timeout
    from wait_for_completion.
    
    Signed-off-by: Koji Matsuoka <koji.matsuoka.xm@renesas.com>
    Signed-off-by: Yoshihiro Kaneko <ykaneko0929@gmail.com>
    Signed-off-by: Guennadi Liakhovetski <g.liakhovetski@gmx.de>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>

commit 2a700d8edffdbfb8200332d96c3147e042b337f1
Author: Hans Verkuil <hans.verkuil@cisco.com>
Date:   Mon Apr 13 11:18:51 2015 -0300

    [media] marvell-ccic: fix Y'CbCr ordering
    
    Various formats had their byte ordering implemented incorrectly, and
    the V4L2_PIX_FMT_UYVY is actually impossible to create, instead you
    get V4L2_PIX_FMT_YVYU.
    
    This was working before commit ad6ac452227b7cb93ac79beec092850d178740b1
    ("add new formats support for marvell-ccic driver"). That commit broke
    the original format support and the OLPC XO-1 laptop showed wrong
    colors ever since (if you are crazy enough to attempt to run the latest
    kernel on it, like I did).
    
    The email addresses of the authors of that patch are no longer valid,
    so without a way to reach them and ask them about their test setup
    I am going with what I can test on the OLPC laptop.
    
    If this breaks something for someone on their non-OLPC setup, then
    contact the linux-media mailinglist. My suspicion however is that
    that commit went in untested.
    
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Acked-by: Jonathan Corbet <corbet@lwn.net>
    Cc: <stable@vger.kernel.org>      # for v3.19 and up
    Signed-off-by: Hans Verkuil <hans.verkuil@cisco.com>
    Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>