origin
GIT 25364a9e54fb8296837061bf684b76d20eec01fb

commit 2078665a7e12df5d8ab4d254eac69e15959271e6
Author: Benjamin Tissoires <benjamin.tissoires@redhat.com>
Date:   Tue Dec 1 10:26:24 2015 +0100

    HID: lg: restrict filtering out of first interface to G29 only
    
    Looks like 29fae1c85 ("HID: logitech: Add support for G29") was a little
    bit aggressive and broke other devices.
    
    Fixes: https://bugzilla.kernel.org/show_bug.cgi?id=108121
    
    Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

commit 48111b79b77f9fb1f139e1878b3cfcd56b46b789
Author: Geert Uytterhoeven <geert+renesas@glider.be>
Date:   Wed Nov 25 13:52:13 2015 +0100

    pinctrl: sh-pfc: sh7734: Add missing cfg macro parameter to fix build
    
    When building for SH7734:
    
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:586:1: error: macro "_GP_DATA" passed 5 arguments, but takes just 4
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:586:2: error: '_GP_DATA' undeclared here (not in a function)
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:586:1: error: macro "_GP_DATA" passed 5 arguments, but takes just 4
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:586:1: error: macro "_GP_DATA" passed 5 arguments, but takes just 4
        ...
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2389:1: error: macro "_GP_INOUTSEL" passed 5 arguments, but takes just 4
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2389:53: error: '_GP_INOUTSEL' undeclared here (not in a function)
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2389:2: warning: initialization makes integer from pointer without a cast [enabled by default]
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2389:2: warning: (near initialization for '(anonymous)[0]') [enabled by default]
        ...
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2416:1: error: macro "_GP_INDT" passed 5 arguments, but takes just 4
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2416:47: error: '_GP_INDT' undeclared here (not in a function)
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2416:2: warning: initialization makes integer from pointer without a cast [enabled by default]
        drivers/pinctrl/sh-pfc/pfc-sh7734.c:2416:2: warning: (near initialization for '(anonymous)[0]') [enabled by default]
        ...
    
    Add the missing "cfg" macro parameters to the sh7734-specific
    _GP_DATA(), _GP_INOUTSEL(), and _GP_INDT() macros to fix this.
    
    Fixes: 22768fc60abbf58b ("pinctrl: sh-pfc: Add macros defining GP ports with config flags")
    Signed-off-by: Geert Uytterhoeven <geert+renesas@glider.be>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit c86576ea114a9a881cf7328dc7181052070ca311
Author: Guenter Roeck <linux@roeck-us.net>
Date:   Sat Nov 28 08:52:04 2015 -0800

    mn10300: Select CONFIG_HAVE_UID16 to fix build failure
    
    mn10300 builds fail with
    
    fs/stat.c: In function 'cp_old_stat':
    fs/stat.c:163:2: error: 'old_uid_t' undeclared
    
    ipc/util.c: In function 'ipc64_perm_to_ipc_perm':
    ipc/util.c:540:2: error: 'old_uid_t' undeclared
    
    Select CONFIG_HAVE_UID16 and remove local definition of CONFIG_UID16
    to fix the problem.
    
    Fixes: fbc416ff8618 ("arm64: fix building without CONFIG_UID16")
    Cc: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Arnd Bergmann <arnd@arndb.de>
    Acked-by: Acked-by: David Howells <dhowells@redhat.com>
    Signed-off-by: Guenter Roeck <linux@roeck-us.net>

commit 000255b7dfc3119c13f388f179d6fc19cd00eada
Author: Grygorii Strashko <grygorii.strashko@ti.com>
Date:   Fri Nov 20 15:35:14 2015 +0200

    gpio: omap: drop omap1 mpuio specific irq_mask/unmask callbacks
    
    Originally OMAP MPUIO GPIO irqchip was implemented using Generic irq
    chip, but after set of reworks Generic irq chip code was replaced by
    common OMAP GPIO implementation and finally removed by
    commit d2d05c65c40e ("gpio: omap: Fix regression for MPUIO interrupts").
    Unfortunately, above commit left .irq_mask/unmask callbacks assigned
    as below for MPUIO GPIO case:
    	irqc->irq_mask = irq_gc_mask_set_bit;
    	irqc->irq_unmask = irq_gc_mask_clr_bit;
    
    This now causes boot failure on OMAP1 platforms, after
    commit 450fa54cfd66 ("gpio: omap: convert to use generic irq handler")
    which forces these callbacks to be called during GPIO IRQs mapping
    from gpiochip_irq_map:
    
    Unable to handle kernel NULL pointer dereference at virtual address 00000000
    pgd = c0004000
    [00000000] *pgd=00000000
    Internal error: Oops: 75 [#1] ARM
    Modules linked in:
    CPU: 0 PID: 1 Comm: swapper Not tainted 4.4.0-rc1-e3-los_afe0c+-00002-g25379c0-dirty #1
    Hardware name: Amstrad E3 (Delta)
    task: c1836000 ti: c1838000 task.ti: c1838000
    PC is at irq_gc_mask_set_bit+0x1c/0x60
    LR is at __irq_do_set_handler+0x118/0x15c
    pc : [<c004848c>]    lr : [<c0047d4c>]    psr: 600000d3
    sp : c1839c90  ip : c1862c64  fp : c1839c9c
    r10: 00000000  r9 : c0411950  r8 : c0411bbc
    r7 : 00000000  r6 : c185c310  r5 : c00444e8  r4 : c185c300
    r3 : c1854b50  r2 : 00000000  r1 : 00000000  r0 : c185c310
    Flags: nZCv  IRQs off  FIQs off  Mode SVC_32  ISA ARM  Segment kernel
    Control: 0000317f  Table: 10004000  DAC: 00000057
    Process swapper (pid: 1, stack limit = 0xc1838190)
    Stack: (0xc1839c90 to 0xc183a000)
    
    [...]
    
    Backtrace:
    [<c0048470>] (irq_gc_mask_set_bit) from [<c0047d4c>] (__irq_do_set_handler+0x118/0x15c)
    [<c0047c34>] (__irq_do_set_handler) from [<c0047dd4>] (__irq_set_handler+0x44/0x5c)
     r6:00000000 r5:c00444e8 r4:c185c300
    [<c0047d90>] (__irq_set_handler) from [<c0047e1c>] (irq_set_chip_and_handler_name+0x30/0x34)
     r7:00000050 r6:00000000 r5:c00444e8 r4:00000050
    [<c0047dec>] (irq_set_chip_and_handler_name) from [<c01b345c>] (gpiochip_irq_map+0x3c/0x8c)
     r7:00000050 r6:00000000 r5:00000050 r4:c1862c64
    [<c01b3420>] (gpiochip_irq_map) from [<c0049670>] (irq_domain_associate+0x7c/0x1c4)
     r5:c185c310 r4:c185cb00
    [<c00495f4>] (irq_domain_associate) from [<c0049894>] (irq_domain_add_simple+0x98/0xc0)
     r8:c0411bbc r7:c185cb00 r6:00000050 r5:00000010 r4:00000001
    [<c00497fc>] (irq_domain_add_simple) from [<c01b3328>] (_gpiochip_irqchip_add+0x64/0x10c)
     r7:c1862c64 r6:c0419280 r5:c1862c64 r4:c1854b50
    [<c01b32c4>] (_gpiochip_irqchip_add) from [<c01b79f4>] (omap_gpio_probe+0x2fc/0x63c)
     r5:c1854b50 r4:c1862c10
    [<c01b76f8>] (omap_gpio_probe) from [<c01fcf58>] (platform_drv_probe+0x2c/0x64)
     r10:00000000 r9:c03e45e8 r8:00000000 r7:c0419294 r6:c0411984 r5:c0419294
     r4:c0411950
    [<c01fcf2c>] (platform_drv_probe) from [<c01fb668>] (really_probe+0x160/0x29c)
    
    Hence, fix it by remove obsolete callbacks assignment. After this
    change 	omap_gpio_mask_irq()/omap_gpio_unmask_irq() will be used
    for MPUIO IRQs masking, but this now happens anyway from
    omap_gpio_irq_startup/shutdown().
    
    Cc: Tony Lindgren <tony@atomide.com>
    Fixes: commit d2d05c65c40e ("gpio: omap: Fix regression for MPUIO interrupts")
    Reported-by: Aaro Koskinen <aaro.koskinen@iki.fi>
    Signed-off-by: Grygorii Strashko <grygorii.strashko@ti.com>
    Acked-by: Santosh Shilimkar <ssantosh@kernel.org>
    Tested-by: Aaro Koskinen <aaro.koskinen@iki.fi>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit d06165b329c04c8050c4b744c05ec61046709490
Author: Vladimir Zapolskiy <vz@mleia.com>
Date:   Wed Nov 11 14:36:53 2015 +0200

    gpiolib: fix oops, if gpio name is NULL
    
    Commit c0017ed71966 ("gpio: Introduce gpio descriptor 'name'") causes
    OOPS on boot on LPC32xx boards:
    
        Unable to handle kernel NULL pointer dereference at virtual address 00000000
        CPU: 0 PID: 1 Comm: swapper Not tainted 4.3.0+ #707
        Hardware name: LPC32XX SoC (Flattened Device Tree)
        task: c381baa0 ti: c381e000 task.ti: c381e000
        PC is at strcmp+0x10/0x40
        LR is at gpiochip_add+0x3d0/0x4d4
        pc : [<>]    lr : [<>]    psr: a0000093
        sp : c381fd60  ip : c381fd70  fp : c381fd6c
    
        [snip]
    
        Backtrace:
        [<>] (strcmp) from [<>] (gpiochip_add+0x3d0/0x4d4)
        [<>] (gpiochip_add) from [<>] (lpc32xx_gpio_probe+0x44/0x60)
        [<>] (lpc32xx_gpio_probe) from [<>] (platform_drv_probe+0x40/0x8c)
        [<>] (platform_drv_probe) from [<>] (driver_probe_device+0x110/0x294)
        [<>] (driver_probe_device) from [<>] (__driver_attach+0x70/0x94)
        [<>] (__driver_attach) from [<>] (bus_for_each_dev+0x74/0x98)
        [<>] (bus_for_each_dev) from [<>] (driver_attach+0x20/0x28)
        [<>] (driver_attach) from [<>] (bus_add_driver+0xd4/0x1f0)
        [<>] (bus_add_driver) from [<>] (driver_register+0xa4/0xe8)
        [<>] (driver_register) from [<>] (__platform_driver_register+0x38/0x4c)
        [<>] (__platform_driver_register) from [<>] (lpc32xx_gpio_driver_init+0x18/0x20)
        [<>] (lpc32xx_gpio_driver_init) from [<>] (do_one_initcall+0x108/0x1c8)
        [<>] (do_one_initcall) from [<>] (kernel_init_freeable+0x10c/0x1d4)
        [<>] (kernel_init_freeable) from [<>] (kernel_init+0x10/0xec)
        [<>] (kernel_init) from [<>] (ret_from_fork+0x14/0x24)
    
    This is caused by the fact that at the moment some GPIO names are set
    to NULL, there is a hole in linear representation of one GPI bank, see
    drivers/gpio/gpio-lpc32xx.c / gpi_p3_names[] for details.
    
    The same problem most probably affects also gpio-cs5535.c, see
    cs5535_gpio_names[].
    
    Signed-off-by: Vladimir Zapolskiy <vz@mleia.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit f42f79af16ce2e8fff49ea9ba4949d3abdd6f26f
Author: Suman Anna <s-anna@ti.com>
Date:   Wed Sep 16 19:29:18 2015 -0500

    remoteproc: fix memory leak of remoteproc ida cache layers
    
    The remoteproc core uses a static ida named rproc_dev_index for
    assigning an automatic index number to a registered remoteproc.
    The ida core may allocate some internal idr cache layers and ida
    bitmap upon any ida allocation, and all these layers are truely
    freed only upon the ida destruction. The rproc_dev_index ida is
    not destroyed at present, leading to a memory leak when using the
    remoteproc core as a module and atleast one rproc device is
    registered and unregistered.
    
    Fix this by invoking ida_destroy() in the remoteproc core module
    exit.
    
    Signed-off-by: Suman Anna <s-anna@ti.com>
    Signed-off-by: Ohad Ben-Cohen <ohad@wizery.com>

commit 92792e48e2ae6051af30468a87994b5432da2f06
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Fri Nov 20 18:26:07 2015 +0100

    remoteproc: avoid stack overflow in debugfs file
    
    Recent gcc versions warn about reading from a negative offset of
    an on-stack array:
    
    drivers/remoteproc/remoteproc_debugfs.c: In function 'rproc_recovery_write':
    drivers/remoteproc/remoteproc_debugfs.c:167:9: warning: 'buf[4294967295u]' may be used uninitialized in this function [-Wmaybe-uninitialized]
    
    I don't see anything in sys_write() that prevents us from
    being called with a zero 'count' argument, so we should
    add an extra check in rproc_recovery_write() to prevent the
    access and avoid the warning.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Fixes: 2e37abb89a2e ("remoteproc: create a 'recovery' debugfs entry")
    Signed-off-by: Ohad Ben-Cohen <ohad@wizery.com>

commit bd1b7cd360f529394936f28746eb4aaa12d6770a
Author: Steven Rostedt (Red Hat) <rostedt@goodmis.org>
Date:   Mon Nov 23 17:35:24 2015 -0500

    ring-buffer: Put back the length if crossed page with add_timestamp
    
    Commit fcc742eaad7c "ring-buffer: Add event descriptor to simplify passing
    data" added a descriptor that holds various data instead of passing around
    several variables through parameters. The problem was that one of the
    parameters was modified in a function and the code was designed not to have
    an effect on that modified  parameter. Now that the parameter is a
    descriptor and any modifications to it are non-volatile, the size of the
    data could be unnecessarily expanded.
    
    Remove the extra space added if a timestamp was added and the event went
    across the page.
    
    Cc: stable@vger.kernel.org # 4.3+
    Fixes: fcc742eaad7c "ring-buffer: Add event descriptor to simplify passing data"
    Signed-off-by: Steven Rostedt <rostedt@goodmis.org>

commit b81f472a208d3e2b4392faa6d17037a89442f4ce
Author: Steven Rostedt (Red Hat) <rostedt@goodmis.org>
Date:   Mon Nov 23 10:35:36 2015 -0500

    ring-buffer: Update read stamp with first real commit on page
    
    Do not update the read stamp after swapping out the reader page from the
    write buffer. If the reader page is swapped out of the buffer before an
    event is written to it, then the read_stamp may get an out of date
    timestamp, as the page timestamp is updated on the first commit to that
    page.
    
    rb_get_reader_page() only returns a page if it has an event on it, otherwise
    it will return NULL. At that point, check if the page being returned has
    events and has not been read yet. Then at that point update the read_stamp
    to match the time stamp of the reader page.
    
    Cc: stable@vger.kernel.org # 2.6.30+
    Signed-off-by: Steven Rostedt <rostedt@goodmis.org>

commit 0d51571d51ea8eb72b903b2a4f3f43a38e7bc718
Author: Jimmy Berry <jimmy@boombatower.com>
Date:   Fri Nov 20 01:10:28 2015 -0600

    HID: usbhid: add Logitech G710+ keyboard quirk NOGET
    
    Without quirk keyboard repeats '6' until volume control is used since it
    indicates the key is pressed without ever releasing.
    
    Signed-off-by: Jimmy Berry <jimmy@boombatower.com>
    Signed-off-by: Jiri Kosina <jkosina@suse.cz>

commit f97c2309667b501c03fcc1c8b3595f5ca0a1ff01
Author: Hongzhou Yang <hongzhou.yang@mediatek.com>
Date:   Tue Nov 17 14:17:13 2015 -0800

    pinctrl: mediatek: Add get_direction support.
    
    Since Linux gpio framework return 0 for output, 1 for input.
    But HW use 0 stands for input, and 1 stands for output.
    So use negative to correct it.
    
    And gpio_chip.get is used to get input value, no need to get
    output value, so removing it.
    
    Signed-off-by: Hongzhou Yang <hongzhou.yang@mediatek.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit c3dd25cc78150d4db8c7a1842884553202d1fd43
Author: Arnd Bergmann <arnd@arndb.de>
Date:   Mon Nov 16 17:41:18 2015 +0100

    pinctrl: fix qcom ssbi drivers for 64-bit compilation
    
    When building pinctrl-ssbi-gpio and pinctrl-ssbi-mpp for ARM64, we get
    a compile warning about invalid types:
    
    drivers/pinctrl/qcom/pinctrl-ssbi-gpio.c: In function 'pm8xxx_gpio_probe':
    drivers/pinctrl/qcom/pinctrl-ssbi-gpio.c:675:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    drivers/pinctrl/qcom/pinctrl-ssbi-mpp.c: In function 'pm8xxx_mpp_probe':
    drivers/pinctrl/qcom/pinctrl-ssbi-mpp.c:766:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
    
    This changes the code so we cast the pointer to 'unsigned long', which
    is the right thing to do here.
    
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Reviewed-by: Bjorn Andersson <bjorn.andersson@sonymobile.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit b59d5fb7e9c7b145eae1119af04b7c450efaa11b
Author: Suzuki K. Poulose <suzuki.poulose@arm.com>
Date:   Mon Nov 16 16:07:10 2015 +0000

    gpio-tegra: Do not create the debugfs entry by default
    
    The tegra gpio driver creates the debugfs entry irrespective of
    whether the device exists or not. This is enabled on an arm64_defconfig
    and leaves an entry in debugfs on all platforms where it is not
    useful. This patch fixes the issue by creating the entry only when
    a device exists.
    
    Signed-off-by: Suzuki K. Poulose <suzuki.poulose@arm.com>
    Acked-by: Thierry Reding <treding@nvidia.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 0563df2ce72b5d21217223e73f56ecfcacffb639
Author: Vaishali Thakkar <vthakkar1994@gmail.com>
Date:   Sun Nov 15 09:34:23 2015 +0530

    pinctrl: imx1-core: add missing of_node_put
    
    for_each_child_of_node performs an of_node_get on each iteration,
    so of_node_put is required on break out of the loop.
    
    This is done using Coccinelle. And semantic patch used for this is
    as follows:
    
    @@
    expression root,e;
    local idexpression child;
    @@
    
     for_each_child_of_node(root, child) {
       ... when != of_node_put(child)
           when != e = child
    (
       return child;
    |
    +  of_node_put(child);
    ?  return ...;
    )
       ...
     }
    
    Signed-off-by: Vaishali Thakkar <vthakkar1994@gmail.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 5664de25fa8ad2f06d6d7dd44df61023e1aaaa14
Author: LABBE Corentin <clabbe.montjoie@gmail.com>
Date:   Wed Nov 11 21:27:36 2015 +0100

    gpio: palmas: fix a possible NULL dereference
    
    of_match_device could return NULL, and so cause a NULL pointer
    dereference later.
    
    Reported-by: coverity (CID 1130700)
    Signed-off-by: LABBE Corentin <clabbe.montjoie@gmail.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 853f0cb8603486a8ba17d5b728b52a9b4b029698
Author: LABBE Corentin <clabbe.montjoie@gmail.com>
Date:   Wed Nov 11 21:27:35 2015 +0100

    gpio: syscon: fix a possible NULL dereference
    
    of_match_device could return NULL, and so cause a NULL pointer
    dereference later at line 199:
    priv->flags = of_id->data;
    
    Reported-by: coverity (CID 1324140)
    Signed-off-by: LABBE Corentin <clabbe.montjoie@gmail.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 56880a243c85668762dfec69b878862f86be6f04
Author: LABBE Corentin <clabbe.montjoie@gmail.com>
Date:   Wed Nov 11 21:27:34 2015 +0100

    gpio: 74xx: fix a possible NULL dereference
    
    of_match_device could return NULL, and so cause a NULL pointer
    dereference later at line 132:
    priv->flags = (uintptr_t) of_id->data;
    
    Reported-by: coverity (CID 1324141)
    Signed-off-by: LABBE Corentin <clabbe.montjoie@gmail.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>

commit 932cb839628e9b4660672e93280a41da044601e1
Author: Masahiro Yamada <yamada.masahiro@socionext.com>
Date:   Thu Nov 5 15:46:03 2015 +0900

    pinctrl: remove redundant if conditional from Kconfig
    
    The whole menu is guarded by
    
      menu "Pin controllers"
              depends on PINCTRL
          ...
      endmenu
    
    The if conditional outside of it is redundant.
    
    Signed-off-by: Masahiro Yamada <yamada.masahiro@socionext.com>
    Signed-off-by: Linus Walleij <linus.walleij@linaro.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>