lib: use correct format string for find-bit tests
The cycles_t definition is architecture specific, which causes a link
error on all architectures that use a 'long long' or 'int' type for it:

lib/test_find_bit.c: In function 'test_find_last_bit':
include/linux/kern_levels.h:5:18: error: format '%ld' expects argument of type 'long int', but argument 2 has type 'cycles_t {aka long long unsigned int}' [-Werror=format=]

This adds an explicit cast to 'u64' for it, which lets us use
'%llu' everywhere.

Link: http://lkml.kernel.org/r/20171113135605.3166307-1-arnd@arndb.de
Fixes: 09588b1f1d58 ("lib: test module for find_*_bit() functions")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Cc: Yury Norov <ynorov@caviumnetworks.com>
Cc: Clement Courbet <courbet@google.com>
Cc: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>