sysvipc-make-get_maxid-o1-again-checkpatch-fixes
ERROR: space required before the open parenthesis '('
#110: FILE: ipc/util.c:439:
+			if(lid == -1)

total: 1 errors, 0 warnings, 113 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/sysvipc-make-get_maxid-o1-again.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Davidlohr Bueso <dave@stgolabs.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>