mm-vmalloc-fix-vmalloc-users-tracking-properly-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#4: 
1f5307b1e094 ("mm, vmalloc: properly track vmalloc users") has pulled

WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#12: 
>> arch/m68k/include/asm/mcf_pgtable.h:339:43: error: 'init_mm' undeclared (first use in this function)

ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#36: 
This patch reverts 1f5307b1e094 and reimplements the original fix in a

WARNING: line over 80 characters
#71: FILE: include/linux/vmalloc.h:85:
+static inline void *__vmalloc_node_flags_caller(unsigned long size, int node, gfp_t flags, void* caller)

ERROR: "foo* bar" should be "foo *bar"
#71: FILE: include/linux/vmalloc.h:85:
+static inline void *__vmalloc_node_flags_caller(unsigned long size, int node, gfp_t flags, void* caller)

ERROR: "foo* bar" should be "foo *bar"
#92: FILE: include/linux/vmalloc.h:96:
+					int node, gfp_t flags, void* caller);

WARNING: line over 80 characters
#143: FILE: mm/vmalloc.c:1820:
+void *__vmalloc_node_flags_caller(unsigned long size, int node, gfp_t flags, void *caller)

total: 4 errors, 3 warnings, 80 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-vmalloc-fix-vmalloc-users-tracking-properly.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Michal Hocko <mhocko@suse.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>