vmalloc-fix-__gfp_highmem-usage-for-vmalloc_32-on-32b-systems-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#5: 
drivers/media/common/saa7146/saa7146_core.c since 19809c2da28a ("mm,

ERROR: Macros with complex values should be enclosed in parentheses
#45: FILE: mm/vmalloc.c:1954:
+#define GFP_VMALLOC32 GFP_DMA32 | GFP_KERNEL

total: 2 errors, 0 warnings, 12 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/vmalloc-fix-__gfp_highmem-usage-for-vmalloc_32-on-32b-systems.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Michal Hocko <mhocko@suse.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>