mm: fix dump_vma() compilation
dump_vma() was written to access fields within vma->vm_page_prot. However,
pgprot_t is sometimes a scalar and sometimes a struct (At least on ARM;
see arch/arm/include/asm/pgtable-2level-types.h). use macro pgprot_val()
to get the value, so the code is immune to these differences.

This fixes:
mm/page_alloc.c: In function `dump_vma':
mm/page_alloc.c:6742:46: error: request for member `pgprot' in something not a structure or union

The cast is required to avoid:

mm/page_alloc.c: In function `dump_vma':
mm/page_alloc.c:6745:3: warning: format `%lx' expects argument of type `long unsigned int', but argument 8 has type `pgprot_t' [-Wformat]

Fixes: 658f7da49d34 ("mm: introduce dump_vma")
Signed-off-by: Stephen Warren <swarren@nvidia.com>
Cc: Sasha Levin <sasha.levin@oracle.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>